import { z } from 'zod'
import { Activity, ActivityType, Activity_Filter, Activity_OrderBy, BlockChangedFilter, Block_Height, Category, Category_Filter, Category_OrderBy, Country, Country_Filter, Country_OrderBy, Listing, Listing_Filter, Listing_OrderBy, OrderDirection, Project, Project_Filter, Project_OrderBy, Purchase, Purchase_Filter, Purchase_OrderBy, User, User_Filter, User_OrderBy, _Block_, _Meta_, _SubgraphErrorPolicy_ } from '../types/marketplace.types'

type Properties<T> = Required<{
  [K in keyof T]: z.ZodType<T[K], any, T[K]>;
}>;

type definedNonNullAny = {};

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny => v !== undefined && v !== null;

export const definedNonNullAnySchema = z.any().refine((v) => isDefinedNonNullAny(v));

export const ActivityTypeSchema = z.nativeEnum(ActivityType);

export const Activity_OrderBySchema = z.nativeEnum(Activity_OrderBy);

export const Category_OrderBySchema = z.nativeEnum(Category_OrderBy);

export const Country_OrderBySchema = z.nativeEnum(Country_OrderBy);

export const Listing_OrderBySchema = z.nativeEnum(Listing_OrderBy);

export const OrderDirectionSchema = z.nativeEnum(OrderDirection);

export const Project_OrderBySchema = z.nativeEnum(Project_OrderBy);

export const Purchase_OrderBySchema = z.nativeEnum(Purchase_OrderBy);

export const User_OrderBySchema = z.nativeEnum(User_OrderBy);

export const _SubgraphErrorPolicy_Schema = z.nativeEnum(_SubgraphErrorPolicy_);

export function ActivitySchema(): z.ZodObject<Properties<Activity>> {
  return z.object({
    __typename: z.literal('Activity').optional(),
    activityType: ActivityTypeSchema,
    amount: definedNonNullAnySchema.nullish(),
    buyer: UserSchema().nullish(),
    id: definedNonNullAnySchema,
    listing: ListingSchema().nullish(),
    previousAmount: definedNonNullAnySchema.nullish(),
    previousPrice: definedNonNullAnySchema.nullish(),
    price: definedNonNullAnySchema.nullish(),
    project: ProjectSchema().nullish(),
    seller: UserSchema(),
    timeStamp: definedNonNullAnySchema.nullish(),
    user: UserSchema().nullish()
  })
}

export function Activity_FilterSchema(): z.ZodObject<Properties<Activity_Filter>> {
  return z.object({
    _change_block: BlockChangedFilterSchema().nullish(),
    activityType: ActivityTypeSchema.nullish(),
    activityType_in: z.array(ActivityTypeSchema).nullish(),
    activityType_not: ActivityTypeSchema.nullish(),
    activityType_not_in: z.array(ActivityTypeSchema).nullish(),
    amount: definedNonNullAnySchema.nullish(),
    amount_gt: definedNonNullAnySchema.nullish(),
    amount_gte: definedNonNullAnySchema.nullish(),
    amount_in: z.array(definedNonNullAnySchema).nullish(),
    amount_lt: definedNonNullAnySchema.nullish(),
    amount_lte: definedNonNullAnySchema.nullish(),
    amount_not: definedNonNullAnySchema.nullish(),
    amount_not_in: z.array(definedNonNullAnySchema).nullish(),
    and: z.array(Activity_FilterSchema().nullable()).nullish(),
    buyer: definedNonNullAnySchema.nullish(),
    buyer_: User_FilterSchema().nullish(),
    buyer_contains: definedNonNullAnySchema.nullish(),
    buyer_contains_nocase: definedNonNullAnySchema.nullish(),
    buyer_ends_with: definedNonNullAnySchema.nullish(),
    buyer_ends_with_nocase: definedNonNullAnySchema.nullish(),
    buyer_gt: definedNonNullAnySchema.nullish(),
    buyer_gte: definedNonNullAnySchema.nullish(),
    buyer_in: z.array(definedNonNullAnySchema).nullish(),
    buyer_lt: definedNonNullAnySchema.nullish(),
    buyer_lte: definedNonNullAnySchema.nullish(),
    buyer_not: definedNonNullAnySchema.nullish(),
    buyer_not_contains: definedNonNullAnySchema.nullish(),
    buyer_not_contains_nocase: definedNonNullAnySchema.nullish(),
    buyer_not_ends_with: definedNonNullAnySchema.nullish(),
    buyer_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    buyer_not_in: z.array(definedNonNullAnySchema).nullish(),
    buyer_not_starts_with: definedNonNullAnySchema.nullish(),
    buyer_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    buyer_starts_with: definedNonNullAnySchema.nullish(),
    buyer_starts_with_nocase: definedNonNullAnySchema.nullish(),
    id: definedNonNullAnySchema.nullish(),
    id_contains: definedNonNullAnySchema.nullish(),
    id_contains_nocase: definedNonNullAnySchema.nullish(),
    id_ends_with: definedNonNullAnySchema.nullish(),
    id_ends_with_nocase: definedNonNullAnySchema.nullish(),
    id_gt: definedNonNullAnySchema.nullish(),
    id_gte: definedNonNullAnySchema.nullish(),
    id_in: z.array(definedNonNullAnySchema).nullish(),
    id_lt: definedNonNullAnySchema.nullish(),
    id_lte: definedNonNullAnySchema.nullish(),
    id_not: definedNonNullAnySchema.nullish(),
    id_not_contains: definedNonNullAnySchema.nullish(),
    id_not_contains_nocase: definedNonNullAnySchema.nullish(),
    id_not_ends_with: definedNonNullAnySchema.nullish(),
    id_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    id_not_in: z.array(definedNonNullAnySchema).nullish(),
    id_not_starts_with: definedNonNullAnySchema.nullish(),
    id_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    id_starts_with: definedNonNullAnySchema.nullish(),
    id_starts_with_nocase: definedNonNullAnySchema.nullish(),
    listing: definedNonNullAnySchema.nullish(),
    listing_: Listing_FilterSchema().nullish(),
    listing_contains: definedNonNullAnySchema.nullish(),
    listing_contains_nocase: definedNonNullAnySchema.nullish(),
    listing_ends_with: definedNonNullAnySchema.nullish(),
    listing_ends_with_nocase: definedNonNullAnySchema.nullish(),
    listing_gt: definedNonNullAnySchema.nullish(),
    listing_gte: definedNonNullAnySchema.nullish(),
    listing_in: z.array(definedNonNullAnySchema).nullish(),
    listing_lt: definedNonNullAnySchema.nullish(),
    listing_lte: definedNonNullAnySchema.nullish(),
    listing_not: definedNonNullAnySchema.nullish(),
    listing_not_contains: definedNonNullAnySchema.nullish(),
    listing_not_contains_nocase: definedNonNullAnySchema.nullish(),
    listing_not_ends_with: definedNonNullAnySchema.nullish(),
    listing_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    listing_not_in: z.array(definedNonNullAnySchema).nullish(),
    listing_not_starts_with: definedNonNullAnySchema.nullish(),
    listing_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    listing_starts_with: definedNonNullAnySchema.nullish(),
    listing_starts_with_nocase: definedNonNullAnySchema.nullish(),
    or: z.array(Activity_FilterSchema().nullable()).nullish(),
    previousAmount: definedNonNullAnySchema.nullish(),
    previousAmount_gt: definedNonNullAnySchema.nullish(),
    previousAmount_gte: definedNonNullAnySchema.nullish(),
    previousAmount_in: z.array(definedNonNullAnySchema).nullish(),
    previousAmount_lt: definedNonNullAnySchema.nullish(),
    previousAmount_lte: definedNonNullAnySchema.nullish(),
    previousAmount_not: definedNonNullAnySchema.nullish(),
    previousAmount_not_in: z.array(definedNonNullAnySchema).nullish(),
    previousPrice: definedNonNullAnySchema.nullish(),
    previousPrice_gt: definedNonNullAnySchema.nullish(),
    previousPrice_gte: definedNonNullAnySchema.nullish(),
    previousPrice_in: z.array(definedNonNullAnySchema).nullish(),
    previousPrice_lt: definedNonNullAnySchema.nullish(),
    previousPrice_lte: definedNonNullAnySchema.nullish(),
    previousPrice_not: definedNonNullAnySchema.nullish(),
    previousPrice_not_in: z.array(definedNonNullAnySchema).nullish(),
    price: definedNonNullAnySchema.nullish(),
    price_gt: definedNonNullAnySchema.nullish(),
    price_gte: definedNonNullAnySchema.nullish(),
    price_in: z.array(definedNonNullAnySchema).nullish(),
    price_lt: definedNonNullAnySchema.nullish(),
    price_lte: definedNonNullAnySchema.nullish(),
    price_not: definedNonNullAnySchema.nullish(),
    price_not_in: z.array(definedNonNullAnySchema).nullish(),
    project: definedNonNullAnySchema.nullish(),
    project_: Project_FilterSchema().nullish(),
    project_contains: definedNonNullAnySchema.nullish(),
    project_contains_nocase: definedNonNullAnySchema.nullish(),
    project_ends_with: definedNonNullAnySchema.nullish(),
    project_ends_with_nocase: definedNonNullAnySchema.nullish(),
    project_gt: definedNonNullAnySchema.nullish(),
    project_gte: definedNonNullAnySchema.nullish(),
    project_in: z.array(definedNonNullAnySchema).nullish(),
    project_lt: definedNonNullAnySchema.nullish(),
    project_lte: definedNonNullAnySchema.nullish(),
    project_not: definedNonNullAnySchema.nullish(),
    project_not_contains: definedNonNullAnySchema.nullish(),
    project_not_contains_nocase: definedNonNullAnySchema.nullish(),
    project_not_ends_with: definedNonNullAnySchema.nullish(),
    project_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    project_not_in: z.array(definedNonNullAnySchema).nullish(),
    project_not_starts_with: definedNonNullAnySchema.nullish(),
    project_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    project_starts_with: definedNonNullAnySchema.nullish(),
    project_starts_with_nocase: definedNonNullAnySchema.nullish(),
    seller: definedNonNullAnySchema.nullish(),
    seller_: User_FilterSchema().nullish(),
    seller_contains: definedNonNullAnySchema.nullish(),
    seller_contains_nocase: definedNonNullAnySchema.nullish(),
    seller_ends_with: definedNonNullAnySchema.nullish(),
    seller_ends_with_nocase: definedNonNullAnySchema.nullish(),
    seller_gt: definedNonNullAnySchema.nullish(),
    seller_gte: definedNonNullAnySchema.nullish(),
    seller_in: z.array(definedNonNullAnySchema).nullish(),
    seller_lt: definedNonNullAnySchema.nullish(),
    seller_lte: definedNonNullAnySchema.nullish(),
    seller_not: definedNonNullAnySchema.nullish(),
    seller_not_contains: definedNonNullAnySchema.nullish(),
    seller_not_contains_nocase: definedNonNullAnySchema.nullish(),
    seller_not_ends_with: definedNonNullAnySchema.nullish(),
    seller_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    seller_not_in: z.array(definedNonNullAnySchema).nullish(),
    seller_not_starts_with: definedNonNullAnySchema.nullish(),
    seller_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    seller_starts_with: definedNonNullAnySchema.nullish(),
    seller_starts_with_nocase: definedNonNullAnySchema.nullish(),
    timeStamp: definedNonNullAnySchema.nullish(),
    timeStamp_gt: definedNonNullAnySchema.nullish(),
    timeStamp_gte: definedNonNullAnySchema.nullish(),
    timeStamp_in: z.array(definedNonNullAnySchema).nullish(),
    timeStamp_lt: definedNonNullAnySchema.nullish(),
    timeStamp_lte: definedNonNullAnySchema.nullish(),
    timeStamp_not: definedNonNullAnySchema.nullish(),
    timeStamp_not_in: z.array(definedNonNullAnySchema).nullish(),
    user: definedNonNullAnySchema.nullish(),
    user_: User_FilterSchema().nullish(),
    user_contains: definedNonNullAnySchema.nullish(),
    user_contains_nocase: definedNonNullAnySchema.nullish(),
    user_ends_with: definedNonNullAnySchema.nullish(),
    user_ends_with_nocase: definedNonNullAnySchema.nullish(),
    user_gt: definedNonNullAnySchema.nullish(),
    user_gte: definedNonNullAnySchema.nullish(),
    user_in: z.array(definedNonNullAnySchema).nullish(),
    user_lt: definedNonNullAnySchema.nullish(),
    user_lte: definedNonNullAnySchema.nullish(),
    user_not: definedNonNullAnySchema.nullish(),
    user_not_contains: definedNonNullAnySchema.nullish(),
    user_not_contains_nocase: definedNonNullAnySchema.nullish(),
    user_not_ends_with: definedNonNullAnySchema.nullish(),
    user_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    user_not_in: z.array(definedNonNullAnySchema).nullish(),
    user_not_starts_with: definedNonNullAnySchema.nullish(),
    user_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    user_starts_with: definedNonNullAnySchema.nullish(),
    user_starts_with_nocase: definedNonNullAnySchema.nullish()
  })
}

export function BlockChangedFilterSchema(): z.ZodObject<Properties<BlockChangedFilter>> {
  return z.object({
    number_gte: definedNonNullAnySchema
  })
}

export function Block_HeightSchema(): z.ZodObject<Properties<Block_Height>> {
  return z.object({
    hash: definedNonNullAnySchema.nullish(),
    number: definedNonNullAnySchema.nullish(),
    number_gte: definedNonNullAnySchema.nullish()
  })
}

export function CategorySchema(): z.ZodObject<Properties<Category>> {
  return z.object({
    __typename: z.literal('Category').optional(),
    id: definedNonNullAnySchema
  })
}

export function Category_FilterSchema(): z.ZodObject<Properties<Category_Filter>> {
  return z.object({
    _change_block: BlockChangedFilterSchema().nullish(),
    and: z.array(Category_FilterSchema().nullable()).nullish(),
    id: definedNonNullAnySchema.nullish(),
    id_contains: definedNonNullAnySchema.nullish(),
    id_contains_nocase: definedNonNullAnySchema.nullish(),
    id_ends_with: definedNonNullAnySchema.nullish(),
    id_ends_with_nocase: definedNonNullAnySchema.nullish(),
    id_gt: definedNonNullAnySchema.nullish(),
    id_gte: definedNonNullAnySchema.nullish(),
    id_in: z.array(definedNonNullAnySchema).nullish(),
    id_lt: definedNonNullAnySchema.nullish(),
    id_lte: definedNonNullAnySchema.nullish(),
    id_not: definedNonNullAnySchema.nullish(),
    id_not_contains: definedNonNullAnySchema.nullish(),
    id_not_contains_nocase: definedNonNullAnySchema.nullish(),
    id_not_ends_with: definedNonNullAnySchema.nullish(),
    id_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    id_not_in: z.array(definedNonNullAnySchema).nullish(),
    id_not_starts_with: definedNonNullAnySchema.nullish(),
    id_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    id_starts_with: definedNonNullAnySchema.nullish(),
    id_starts_with_nocase: definedNonNullAnySchema.nullish(),
    or: z.array(Category_FilterSchema().nullable()).nullish()
  })
}

export function CountrySchema(): z.ZodObject<Properties<Country>> {
  return z.object({
    __typename: z.literal('Country').optional(),
    id: definedNonNullAnySchema
  })
}

export function Country_FilterSchema(): z.ZodObject<Properties<Country_Filter>> {
  return z.object({
    _change_block: BlockChangedFilterSchema().nullish(),
    and: z.array(Country_FilterSchema().nullable()).nullish(),
    id: definedNonNullAnySchema.nullish(),
    id_contains: definedNonNullAnySchema.nullish(),
    id_contains_nocase: definedNonNullAnySchema.nullish(),
    id_ends_with: definedNonNullAnySchema.nullish(),
    id_ends_with_nocase: definedNonNullAnySchema.nullish(),
    id_gt: definedNonNullAnySchema.nullish(),
    id_gte: definedNonNullAnySchema.nullish(),
    id_in: z.array(definedNonNullAnySchema).nullish(),
    id_lt: definedNonNullAnySchema.nullish(),
    id_lte: definedNonNullAnySchema.nullish(),
    id_not: definedNonNullAnySchema.nullish(),
    id_not_contains: definedNonNullAnySchema.nullish(),
    id_not_contains_nocase: definedNonNullAnySchema.nullish(),
    id_not_ends_with: definedNonNullAnySchema.nullish(),
    id_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    id_not_in: z.array(definedNonNullAnySchema).nullish(),
    id_not_starts_with: definedNonNullAnySchema.nullish(),
    id_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    id_starts_with: definedNonNullAnySchema.nullish(),
    id_starts_with_nocase: definedNonNullAnySchema.nullish(),
    or: z.array(Country_FilterSchema().nullable()).nullish()
  })
}

export function ListingSchema(): z.ZodObject<Properties<Listing>> {
  return z.object({
    __typename: z.literal('Listing').optional(),
    active: definedNonNullAnySchema.nullish(),
    activities: z.array(ActivitySchema()).nullish(),
    batchPrices: z.array(definedNonNullAnySchema).nullish(),
    batches: z.array(definedNonNullAnySchema).nullish(),
    createdAt: definedNonNullAnySchema.nullish(),
    deleted: definedNonNullAnySchema.nullish(),
    id: definedNonNullAnySchema,
    leftToSell: definedNonNullAnySchema,
    project: ProjectSchema(),
    seller: UserSchema(),
    singleUnitPrice: definedNonNullAnySchema,
    tokenAddress: definedNonNullAnySchema,
    totalAmountToSell: definedNonNullAnySchema,
    updatedAt: definedNonNullAnySchema.nullish()
  })
}

export function Listing_FilterSchema(): z.ZodObject<Properties<Listing_Filter>> {
  return z.object({
    _change_block: BlockChangedFilterSchema().nullish(),
    active: definedNonNullAnySchema.nullish(),
    active_in: z.array(definedNonNullAnySchema).nullish(),
    active_not: definedNonNullAnySchema.nullish(),
    active_not_in: z.array(definedNonNullAnySchema).nullish(),
    activities_: Activity_FilterSchema().nullish(),
    and: z.array(Listing_FilterSchema().nullable()).nullish(),
    batchPrices: z.array(definedNonNullAnySchema).nullish(),
    batchPrices_contains: z.array(definedNonNullAnySchema).nullish(),
    batchPrices_contains_nocase: z.array(definedNonNullAnySchema).nullish(),
    batchPrices_not: z.array(definedNonNullAnySchema).nullish(),
    batchPrices_not_contains: z.array(definedNonNullAnySchema).nullish(),
    batchPrices_not_contains_nocase: z.array(definedNonNullAnySchema).nullish(),
    batches: z.array(definedNonNullAnySchema).nullish(),
    batches_contains: z.array(definedNonNullAnySchema).nullish(),
    batches_contains_nocase: z.array(definedNonNullAnySchema).nullish(),
    batches_not: z.array(definedNonNullAnySchema).nullish(),
    batches_not_contains: z.array(definedNonNullAnySchema).nullish(),
    batches_not_contains_nocase: z.array(definedNonNullAnySchema).nullish(),
    createdAt: definedNonNullAnySchema.nullish(),
    createdAt_gt: definedNonNullAnySchema.nullish(),
    createdAt_gte: definedNonNullAnySchema.nullish(),
    createdAt_in: z.array(definedNonNullAnySchema).nullish(),
    createdAt_lt: definedNonNullAnySchema.nullish(),
    createdAt_lte: definedNonNullAnySchema.nullish(),
    createdAt_not: definedNonNullAnySchema.nullish(),
    createdAt_not_in: z.array(definedNonNullAnySchema).nullish(),
    deleted: definedNonNullAnySchema.nullish(),
    deleted_in: z.array(definedNonNullAnySchema).nullish(),
    deleted_not: definedNonNullAnySchema.nullish(),
    deleted_not_in: z.array(definedNonNullAnySchema).nullish(),
    id: definedNonNullAnySchema.nullish(),
    id_gt: definedNonNullAnySchema.nullish(),
    id_gte: definedNonNullAnySchema.nullish(),
    id_in: z.array(definedNonNullAnySchema).nullish(),
    id_lt: definedNonNullAnySchema.nullish(),
    id_lte: definedNonNullAnySchema.nullish(),
    id_not: definedNonNullAnySchema.nullish(),
    id_not_in: z.array(definedNonNullAnySchema).nullish(),
    leftToSell: definedNonNullAnySchema.nullish(),
    leftToSell_gt: definedNonNullAnySchema.nullish(),
    leftToSell_gte: definedNonNullAnySchema.nullish(),
    leftToSell_in: z.array(definedNonNullAnySchema).nullish(),
    leftToSell_lt: definedNonNullAnySchema.nullish(),
    leftToSell_lte: definedNonNullAnySchema.nullish(),
    leftToSell_not: definedNonNullAnySchema.nullish(),
    leftToSell_not_in: z.array(definedNonNullAnySchema).nullish(),
    or: z.array(Listing_FilterSchema().nullable()).nullish(),
    project: definedNonNullAnySchema.nullish(),
    project_: Project_FilterSchema().nullish(),
    project_contains: definedNonNullAnySchema.nullish(),
    project_contains_nocase: definedNonNullAnySchema.nullish(),
    project_ends_with: definedNonNullAnySchema.nullish(),
    project_ends_with_nocase: definedNonNullAnySchema.nullish(),
    project_gt: definedNonNullAnySchema.nullish(),
    project_gte: definedNonNullAnySchema.nullish(),
    project_in: z.array(definedNonNullAnySchema).nullish(),
    project_lt: definedNonNullAnySchema.nullish(),
    project_lte: definedNonNullAnySchema.nullish(),
    project_not: definedNonNullAnySchema.nullish(),
    project_not_contains: definedNonNullAnySchema.nullish(),
    project_not_contains_nocase: definedNonNullAnySchema.nullish(),
    project_not_ends_with: definedNonNullAnySchema.nullish(),
    project_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    project_not_in: z.array(definedNonNullAnySchema).nullish(),
    project_not_starts_with: definedNonNullAnySchema.nullish(),
    project_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    project_starts_with: definedNonNullAnySchema.nullish(),
    project_starts_with_nocase: definedNonNullAnySchema.nullish(),
    seller: definedNonNullAnySchema.nullish(),
    seller_: User_FilterSchema().nullish(),
    seller_contains: definedNonNullAnySchema.nullish(),
    seller_contains_nocase: definedNonNullAnySchema.nullish(),
    seller_ends_with: definedNonNullAnySchema.nullish(),
    seller_ends_with_nocase: definedNonNullAnySchema.nullish(),
    seller_gt: definedNonNullAnySchema.nullish(),
    seller_gte: definedNonNullAnySchema.nullish(),
    seller_in: z.array(definedNonNullAnySchema).nullish(),
    seller_lt: definedNonNullAnySchema.nullish(),
    seller_lte: definedNonNullAnySchema.nullish(),
    seller_not: definedNonNullAnySchema.nullish(),
    seller_not_contains: definedNonNullAnySchema.nullish(),
    seller_not_contains_nocase: definedNonNullAnySchema.nullish(),
    seller_not_ends_with: definedNonNullAnySchema.nullish(),
    seller_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    seller_not_in: z.array(definedNonNullAnySchema).nullish(),
    seller_not_starts_with: definedNonNullAnySchema.nullish(),
    seller_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    seller_starts_with: definedNonNullAnySchema.nullish(),
    seller_starts_with_nocase: definedNonNullAnySchema.nullish(),
    singleUnitPrice: definedNonNullAnySchema.nullish(),
    singleUnitPrice_gt: definedNonNullAnySchema.nullish(),
    singleUnitPrice_gte: definedNonNullAnySchema.nullish(),
    singleUnitPrice_in: z.array(definedNonNullAnySchema).nullish(),
    singleUnitPrice_lt: definedNonNullAnySchema.nullish(),
    singleUnitPrice_lte: definedNonNullAnySchema.nullish(),
    singleUnitPrice_not: definedNonNullAnySchema.nullish(),
    singleUnitPrice_not_in: z.array(definedNonNullAnySchema).nullish(),
    tokenAddress: definedNonNullAnySchema.nullish(),
    tokenAddress_contains: definedNonNullAnySchema.nullish(),
    tokenAddress_gt: definedNonNullAnySchema.nullish(),
    tokenAddress_gte: definedNonNullAnySchema.nullish(),
    tokenAddress_in: z.array(definedNonNullAnySchema).nullish(),
    tokenAddress_lt: definedNonNullAnySchema.nullish(),
    tokenAddress_lte: definedNonNullAnySchema.nullish(),
    tokenAddress_not: definedNonNullAnySchema.nullish(),
    tokenAddress_not_contains: definedNonNullAnySchema.nullish(),
    tokenAddress_not_in: z.array(definedNonNullAnySchema).nullish(),
    totalAmountToSell: definedNonNullAnySchema.nullish(),
    totalAmountToSell_gt: definedNonNullAnySchema.nullish(),
    totalAmountToSell_gte: definedNonNullAnySchema.nullish(),
    totalAmountToSell_in: z.array(definedNonNullAnySchema).nullish(),
    totalAmountToSell_lt: definedNonNullAnySchema.nullish(),
    totalAmountToSell_lte: definedNonNullAnySchema.nullish(),
    totalAmountToSell_not: definedNonNullAnySchema.nullish(),
    totalAmountToSell_not_in: z.array(definedNonNullAnySchema).nullish(),
    updatedAt: definedNonNullAnySchema.nullish(),
    updatedAt_gt: definedNonNullAnySchema.nullish(),
    updatedAt_gte: definedNonNullAnySchema.nullish(),
    updatedAt_in: z.array(definedNonNullAnySchema).nullish(),
    updatedAt_lt: definedNonNullAnySchema.nullish(),
    updatedAt_lte: definedNonNullAnySchema.nullish(),
    updatedAt_not: definedNonNullAnySchema.nullish(),
    updatedAt_not_in: z.array(definedNonNullAnySchema).nullish()
  })
}

export function ProjectSchema(): z.ZodObject<Properties<Project>> {
  return z.object({
    __typename: z.literal('Project').optional(),
    activities: z.array(ActivitySchema()).nullish(),
    category: CategorySchema().nullish(),
    country: CountrySchema().nullish(),
    id: definedNonNullAnySchema,
    key: definedNonNullAnySchema,
    listings: z.array(ListingSchema()).nullish(),
    methodology: definedNonNullAnySchema,
    name: definedNonNullAnySchema,
    projectAddress: definedNonNullAnySchema,
    projectID: definedNonNullAnySchema,
    projectType: definedNonNullAnySchema,
    region: definedNonNullAnySchema,
    registry: definedNonNullAnySchema,
    updatedAt: definedNonNullAnySchema.nullish(),
    vintage: definedNonNullAnySchema
  })
}

export function Project_FilterSchema(): z.ZodObject<Properties<Project_Filter>> {
  return z.object({
    _change_block: BlockChangedFilterSchema().nullish(),
    activities_: Activity_FilterSchema().nullish(),
    and: z.array(Project_FilterSchema().nullable()).nullish(),
    category: definedNonNullAnySchema.nullish(),
    category_: Category_FilterSchema().nullish(),
    category_contains: definedNonNullAnySchema.nullish(),
    category_contains_nocase: definedNonNullAnySchema.nullish(),
    category_ends_with: definedNonNullAnySchema.nullish(),
    category_ends_with_nocase: definedNonNullAnySchema.nullish(),
    category_gt: definedNonNullAnySchema.nullish(),
    category_gte: definedNonNullAnySchema.nullish(),
    category_in: z.array(definedNonNullAnySchema).nullish(),
    category_lt: definedNonNullAnySchema.nullish(),
    category_lte: definedNonNullAnySchema.nullish(),
    category_not: definedNonNullAnySchema.nullish(),
    category_not_contains: definedNonNullAnySchema.nullish(),
    category_not_contains_nocase: definedNonNullAnySchema.nullish(),
    category_not_ends_with: definedNonNullAnySchema.nullish(),
    category_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    category_not_in: z.array(definedNonNullAnySchema).nullish(),
    category_not_starts_with: definedNonNullAnySchema.nullish(),
    category_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    category_starts_with: definedNonNullAnySchema.nullish(),
    category_starts_with_nocase: definedNonNullAnySchema.nullish(),
    country: definedNonNullAnySchema.nullish(),
    country_: Country_FilterSchema().nullish(),
    country_contains: definedNonNullAnySchema.nullish(),
    country_contains_nocase: definedNonNullAnySchema.nullish(),
    country_ends_with: definedNonNullAnySchema.nullish(),
    country_ends_with_nocase: definedNonNullAnySchema.nullish(),
    country_gt: definedNonNullAnySchema.nullish(),
    country_gte: definedNonNullAnySchema.nullish(),
    country_in: z.array(definedNonNullAnySchema).nullish(),
    country_lt: definedNonNullAnySchema.nullish(),
    country_lte: definedNonNullAnySchema.nullish(),
    country_not: definedNonNullAnySchema.nullish(),
    country_not_contains: definedNonNullAnySchema.nullish(),
    country_not_contains_nocase: definedNonNullAnySchema.nullish(),
    country_not_ends_with: definedNonNullAnySchema.nullish(),
    country_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    country_not_in: z.array(definedNonNullAnySchema).nullish(),
    country_not_starts_with: definedNonNullAnySchema.nullish(),
    country_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    country_starts_with: definedNonNullAnySchema.nullish(),
    country_starts_with_nocase: definedNonNullAnySchema.nullish(),
    id: definedNonNullAnySchema.nullish(),
    id_gt: definedNonNullAnySchema.nullish(),
    id_gte: definedNonNullAnySchema.nullish(),
    id_in: z.array(definedNonNullAnySchema).nullish(),
    id_lt: definedNonNullAnySchema.nullish(),
    id_lte: definedNonNullAnySchema.nullish(),
    id_not: definedNonNullAnySchema.nullish(),
    id_not_in: z.array(definedNonNullAnySchema).nullish(),
    key: definedNonNullAnySchema.nullish(),
    key_contains: definedNonNullAnySchema.nullish(),
    key_contains_nocase: definedNonNullAnySchema.nullish(),
    key_ends_with: definedNonNullAnySchema.nullish(),
    key_ends_with_nocase: definedNonNullAnySchema.nullish(),
    key_gt: definedNonNullAnySchema.nullish(),
    key_gte: definedNonNullAnySchema.nullish(),
    key_in: z.array(definedNonNullAnySchema).nullish(),
    key_lt: definedNonNullAnySchema.nullish(),
    key_lte: definedNonNullAnySchema.nullish(),
    key_not: definedNonNullAnySchema.nullish(),
    key_not_contains: definedNonNullAnySchema.nullish(),
    key_not_contains_nocase: definedNonNullAnySchema.nullish(),
    key_not_ends_with: definedNonNullAnySchema.nullish(),
    key_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    key_not_in: z.array(definedNonNullAnySchema).nullish(),
    key_not_starts_with: definedNonNullAnySchema.nullish(),
    key_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    key_starts_with: definedNonNullAnySchema.nullish(),
    key_starts_with_nocase: definedNonNullAnySchema.nullish(),
    listings_: Listing_FilterSchema().nullish(),
    methodology: definedNonNullAnySchema.nullish(),
    methodology_contains: definedNonNullAnySchema.nullish(),
    methodology_contains_nocase: definedNonNullAnySchema.nullish(),
    methodology_ends_with: definedNonNullAnySchema.nullish(),
    methodology_ends_with_nocase: definedNonNullAnySchema.nullish(),
    methodology_gt: definedNonNullAnySchema.nullish(),
    methodology_gte: definedNonNullAnySchema.nullish(),
    methodology_in: z.array(definedNonNullAnySchema).nullish(),
    methodology_lt: definedNonNullAnySchema.nullish(),
    methodology_lte: definedNonNullAnySchema.nullish(),
    methodology_not: definedNonNullAnySchema.nullish(),
    methodology_not_contains: definedNonNullAnySchema.nullish(),
    methodology_not_contains_nocase: definedNonNullAnySchema.nullish(),
    methodology_not_ends_with: definedNonNullAnySchema.nullish(),
    methodology_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    methodology_not_in: z.array(definedNonNullAnySchema).nullish(),
    methodology_not_starts_with: definedNonNullAnySchema.nullish(),
    methodology_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    methodology_starts_with: definedNonNullAnySchema.nullish(),
    methodology_starts_with_nocase: definedNonNullAnySchema.nullish(),
    name: definedNonNullAnySchema.nullish(),
    name_contains: definedNonNullAnySchema.nullish(),
    name_contains_nocase: definedNonNullAnySchema.nullish(),
    name_ends_with: definedNonNullAnySchema.nullish(),
    name_ends_with_nocase: definedNonNullAnySchema.nullish(),
    name_gt: definedNonNullAnySchema.nullish(),
    name_gte: definedNonNullAnySchema.nullish(),
    name_in: z.array(definedNonNullAnySchema).nullish(),
    name_lt: definedNonNullAnySchema.nullish(),
    name_lte: definedNonNullAnySchema.nullish(),
    name_not: definedNonNullAnySchema.nullish(),
    name_not_contains: definedNonNullAnySchema.nullish(),
    name_not_contains_nocase: definedNonNullAnySchema.nullish(),
    name_not_ends_with: definedNonNullAnySchema.nullish(),
    name_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    name_not_in: z.array(definedNonNullAnySchema).nullish(),
    name_not_starts_with: definedNonNullAnySchema.nullish(),
    name_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    name_starts_with: definedNonNullAnySchema.nullish(),
    name_starts_with_nocase: definedNonNullAnySchema.nullish(),
    or: z.array(Project_FilterSchema().nullable()).nullish(),
    projectAddress: definedNonNullAnySchema.nullish(),
    projectAddress_contains: definedNonNullAnySchema.nullish(),
    projectAddress_gt: definedNonNullAnySchema.nullish(),
    projectAddress_gte: definedNonNullAnySchema.nullish(),
    projectAddress_in: z.array(definedNonNullAnySchema).nullish(),
    projectAddress_lt: definedNonNullAnySchema.nullish(),
    projectAddress_lte: definedNonNullAnySchema.nullish(),
    projectAddress_not: definedNonNullAnySchema.nullish(),
    projectAddress_not_contains: definedNonNullAnySchema.nullish(),
    projectAddress_not_in: z.array(definedNonNullAnySchema).nullish(),
    projectID: definedNonNullAnySchema.nullish(),
    projectID_contains: definedNonNullAnySchema.nullish(),
    projectID_contains_nocase: definedNonNullAnySchema.nullish(),
    projectID_ends_with: definedNonNullAnySchema.nullish(),
    projectID_ends_with_nocase: definedNonNullAnySchema.nullish(),
    projectID_gt: definedNonNullAnySchema.nullish(),
    projectID_gte: definedNonNullAnySchema.nullish(),
    projectID_in: z.array(definedNonNullAnySchema).nullish(),
    projectID_lt: definedNonNullAnySchema.nullish(),
    projectID_lte: definedNonNullAnySchema.nullish(),
    projectID_not: definedNonNullAnySchema.nullish(),
    projectID_not_contains: definedNonNullAnySchema.nullish(),
    projectID_not_contains_nocase: definedNonNullAnySchema.nullish(),
    projectID_not_ends_with: definedNonNullAnySchema.nullish(),
    projectID_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    projectID_not_in: z.array(definedNonNullAnySchema).nullish(),
    projectID_not_starts_with: definedNonNullAnySchema.nullish(),
    projectID_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    projectID_starts_with: definedNonNullAnySchema.nullish(),
    projectID_starts_with_nocase: definedNonNullAnySchema.nullish(),
    projectType: definedNonNullAnySchema.nullish(),
    projectType_contains: definedNonNullAnySchema.nullish(),
    projectType_contains_nocase: definedNonNullAnySchema.nullish(),
    projectType_ends_with: definedNonNullAnySchema.nullish(),
    projectType_ends_with_nocase: definedNonNullAnySchema.nullish(),
    projectType_gt: definedNonNullAnySchema.nullish(),
    projectType_gte: definedNonNullAnySchema.nullish(),
    projectType_in: z.array(definedNonNullAnySchema).nullish(),
    projectType_lt: definedNonNullAnySchema.nullish(),
    projectType_lte: definedNonNullAnySchema.nullish(),
    projectType_not: definedNonNullAnySchema.nullish(),
    projectType_not_contains: definedNonNullAnySchema.nullish(),
    projectType_not_contains_nocase: definedNonNullAnySchema.nullish(),
    projectType_not_ends_with: definedNonNullAnySchema.nullish(),
    projectType_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    projectType_not_in: z.array(definedNonNullAnySchema).nullish(),
    projectType_not_starts_with: definedNonNullAnySchema.nullish(),
    projectType_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    projectType_starts_with: definedNonNullAnySchema.nullish(),
    projectType_starts_with_nocase: definedNonNullAnySchema.nullish(),
    region: definedNonNullAnySchema.nullish(),
    region_contains: definedNonNullAnySchema.nullish(),
    region_contains_nocase: definedNonNullAnySchema.nullish(),
    region_ends_with: definedNonNullAnySchema.nullish(),
    region_ends_with_nocase: definedNonNullAnySchema.nullish(),
    region_gt: definedNonNullAnySchema.nullish(),
    region_gte: definedNonNullAnySchema.nullish(),
    region_in: z.array(definedNonNullAnySchema).nullish(),
    region_lt: definedNonNullAnySchema.nullish(),
    region_lte: definedNonNullAnySchema.nullish(),
    region_not: definedNonNullAnySchema.nullish(),
    region_not_contains: definedNonNullAnySchema.nullish(),
    region_not_contains_nocase: definedNonNullAnySchema.nullish(),
    region_not_ends_with: definedNonNullAnySchema.nullish(),
    region_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    region_not_in: z.array(definedNonNullAnySchema).nullish(),
    region_not_starts_with: definedNonNullAnySchema.nullish(),
    region_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    region_starts_with: definedNonNullAnySchema.nullish(),
    region_starts_with_nocase: definedNonNullAnySchema.nullish(),
    registry: definedNonNullAnySchema.nullish(),
    registry_contains: definedNonNullAnySchema.nullish(),
    registry_contains_nocase: definedNonNullAnySchema.nullish(),
    registry_ends_with: definedNonNullAnySchema.nullish(),
    registry_ends_with_nocase: definedNonNullAnySchema.nullish(),
    registry_gt: definedNonNullAnySchema.nullish(),
    registry_gte: definedNonNullAnySchema.nullish(),
    registry_in: z.array(definedNonNullAnySchema).nullish(),
    registry_lt: definedNonNullAnySchema.nullish(),
    registry_lte: definedNonNullAnySchema.nullish(),
    registry_not: definedNonNullAnySchema.nullish(),
    registry_not_contains: definedNonNullAnySchema.nullish(),
    registry_not_contains_nocase: definedNonNullAnySchema.nullish(),
    registry_not_ends_with: definedNonNullAnySchema.nullish(),
    registry_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    registry_not_in: z.array(definedNonNullAnySchema).nullish(),
    registry_not_starts_with: definedNonNullAnySchema.nullish(),
    registry_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    registry_starts_with: definedNonNullAnySchema.nullish(),
    registry_starts_with_nocase: definedNonNullAnySchema.nullish(),
    updatedAt: definedNonNullAnySchema.nullish(),
    updatedAt_gt: definedNonNullAnySchema.nullish(),
    updatedAt_gte: definedNonNullAnySchema.nullish(),
    updatedAt_in: z.array(definedNonNullAnySchema).nullish(),
    updatedAt_lt: definedNonNullAnySchema.nullish(),
    updatedAt_lte: definedNonNullAnySchema.nullish(),
    updatedAt_not: definedNonNullAnySchema.nullish(),
    updatedAt_not_in: z.array(definedNonNullAnySchema).nullish(),
    vintage: definedNonNullAnySchema.nullish(),
    vintage_gt: definedNonNullAnySchema.nullish(),
    vintage_gte: definedNonNullAnySchema.nullish(),
    vintage_in: z.array(definedNonNullAnySchema).nullish(),
    vintage_lt: definedNonNullAnySchema.nullish(),
    vintage_lte: definedNonNullAnySchema.nullish(),
    vintage_not: definedNonNullAnySchema.nullish(),
    vintage_not_in: z.array(definedNonNullAnySchema).nullish()
  })
}

export function PurchaseSchema(): z.ZodObject<Properties<Purchase>> {
  return z.object({
    __typename: z.literal('Purchase').optional(),
    amount: definedNonNullAnySchema,
    id: definedNonNullAnySchema,
    listing: ListingSchema(),
    price: definedNonNullAnySchema,
    timeStamp: definedNonNullAnySchema,
    user: UserSchema()
  })
}

export function Purchase_FilterSchema(): z.ZodObject<Properties<Purchase_Filter>> {
  return z.object({
    _change_block: BlockChangedFilterSchema().nullish(),
    amount: definedNonNullAnySchema.nullish(),
    amount_gt: definedNonNullAnySchema.nullish(),
    amount_gte: definedNonNullAnySchema.nullish(),
    amount_in: z.array(definedNonNullAnySchema).nullish(),
    amount_lt: definedNonNullAnySchema.nullish(),
    amount_lte: definedNonNullAnySchema.nullish(),
    amount_not: definedNonNullAnySchema.nullish(),
    amount_not_in: z.array(definedNonNullAnySchema).nullish(),
    and: z.array(Purchase_FilterSchema().nullable()).nullish(),
    id: definedNonNullAnySchema.nullish(),
    id_contains: definedNonNullAnySchema.nullish(),
    id_gt: definedNonNullAnySchema.nullish(),
    id_gte: definedNonNullAnySchema.nullish(),
    id_in: z.array(definedNonNullAnySchema).nullish(),
    id_lt: definedNonNullAnySchema.nullish(),
    id_lte: definedNonNullAnySchema.nullish(),
    id_not: definedNonNullAnySchema.nullish(),
    id_not_contains: definedNonNullAnySchema.nullish(),
    id_not_in: z.array(definedNonNullAnySchema).nullish(),
    listing: definedNonNullAnySchema.nullish(),
    listing_: Listing_FilterSchema().nullish(),
    listing_contains: definedNonNullAnySchema.nullish(),
    listing_contains_nocase: definedNonNullAnySchema.nullish(),
    listing_ends_with: definedNonNullAnySchema.nullish(),
    listing_ends_with_nocase: definedNonNullAnySchema.nullish(),
    listing_gt: definedNonNullAnySchema.nullish(),
    listing_gte: definedNonNullAnySchema.nullish(),
    listing_in: z.array(definedNonNullAnySchema).nullish(),
    listing_lt: definedNonNullAnySchema.nullish(),
    listing_lte: definedNonNullAnySchema.nullish(),
    listing_not: definedNonNullAnySchema.nullish(),
    listing_not_contains: definedNonNullAnySchema.nullish(),
    listing_not_contains_nocase: definedNonNullAnySchema.nullish(),
    listing_not_ends_with: definedNonNullAnySchema.nullish(),
    listing_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    listing_not_in: z.array(definedNonNullAnySchema).nullish(),
    listing_not_starts_with: definedNonNullAnySchema.nullish(),
    listing_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    listing_starts_with: definedNonNullAnySchema.nullish(),
    listing_starts_with_nocase: definedNonNullAnySchema.nullish(),
    or: z.array(Purchase_FilterSchema().nullable()).nullish(),
    price: definedNonNullAnySchema.nullish(),
    price_gt: definedNonNullAnySchema.nullish(),
    price_gte: definedNonNullAnySchema.nullish(),
    price_in: z.array(definedNonNullAnySchema).nullish(),
    price_lt: definedNonNullAnySchema.nullish(),
    price_lte: definedNonNullAnySchema.nullish(),
    price_not: definedNonNullAnySchema.nullish(),
    price_not_in: z.array(definedNonNullAnySchema).nullish(),
    timeStamp: definedNonNullAnySchema.nullish(),
    timeStamp_gt: definedNonNullAnySchema.nullish(),
    timeStamp_gte: definedNonNullAnySchema.nullish(),
    timeStamp_in: z.array(definedNonNullAnySchema).nullish(),
    timeStamp_lt: definedNonNullAnySchema.nullish(),
    timeStamp_lte: definedNonNullAnySchema.nullish(),
    timeStamp_not: definedNonNullAnySchema.nullish(),
    timeStamp_not_in: z.array(definedNonNullAnySchema).nullish(),
    user: definedNonNullAnySchema.nullish(),
    user_: User_FilterSchema().nullish(),
    user_contains: definedNonNullAnySchema.nullish(),
    user_contains_nocase: definedNonNullAnySchema.nullish(),
    user_ends_with: definedNonNullAnySchema.nullish(),
    user_ends_with_nocase: definedNonNullAnySchema.nullish(),
    user_gt: definedNonNullAnySchema.nullish(),
    user_gte: definedNonNullAnySchema.nullish(),
    user_in: z.array(definedNonNullAnySchema).nullish(),
    user_lt: definedNonNullAnySchema.nullish(),
    user_lte: definedNonNullAnySchema.nullish(),
    user_not: definedNonNullAnySchema.nullish(),
    user_not_contains: definedNonNullAnySchema.nullish(),
    user_not_contains_nocase: definedNonNullAnySchema.nullish(),
    user_not_ends_with: definedNonNullAnySchema.nullish(),
    user_not_ends_with_nocase: definedNonNullAnySchema.nullish(),
    user_not_in: z.array(definedNonNullAnySchema).nullish(),
    user_not_starts_with: definedNonNullAnySchema.nullish(),
    user_not_starts_with_nocase: definedNonNullAnySchema.nullish(),
    user_starts_with: definedNonNullAnySchema.nullish(),
    user_starts_with_nocase: definedNonNullAnySchema.nullish()
  })
}

export function UserSchema(): z.ZodObject<Properties<User>> {
  return z.object({
    __typename: z.literal('User').optional(),
    activities: z.array(ActivitySchema()).nullish(),
    id: definedNonNullAnySchema,
    listings: z.array(ListingSchema()).nullish(),
    purchases: z.array(PurchaseSchema()).nullish()
  })
}

export function User_FilterSchema(): z.ZodObject<Properties<User_Filter>> {
  return z.object({
    _change_block: BlockChangedFilterSchema().nullish(),
    activities_: Activity_FilterSchema().nullish(),
    and: z.array(User_FilterSchema().nullable()).nullish(),
    id: definedNonNullAnySchema.nullish(),
    id_contains: definedNonNullAnySchema.nullish(),
    id_gt: definedNonNullAnySchema.nullish(),
    id_gte: definedNonNullAnySchema.nullish(),
    id_in: z.array(definedNonNullAnySchema).nullish(),
    id_lt: definedNonNullAnySchema.nullish(),
    id_lte: definedNonNullAnySchema.nullish(),
    id_not: definedNonNullAnySchema.nullish(),
    id_not_contains: definedNonNullAnySchema.nullish(),
    id_not_in: z.array(definedNonNullAnySchema).nullish(),
    listings_: Listing_FilterSchema().nullish(),
    or: z.array(User_FilterSchema().nullable()).nullish(),
    purchases_: Purchase_FilterSchema().nullish()
  })
}

export function _Block_Schema(): z.ZodObject<Properties<_Block_>> {
  return z.object({
    __typename: z.literal('_Block_').optional(),
    hash: definedNonNullAnySchema.nullish(),
    number: definedNonNullAnySchema,
    timestamp: definedNonNullAnySchema.nullish()
  })
}

export function _Meta_Schema(): z.ZodObject<Properties<_Meta_>> {
  return z.object({
    __typename: z.literal('_Meta_').optional(),
    block: _Block_Schema(),
    deployment: definedNonNullAnySchema,
    hasIndexingErrors: definedNonNullAnySchema
  })
}
