export const types = [
  { label: "Agriculture", value: "Agriculture" },
  { label: "Energy Efficiency", value: "Energy Efficiency" },
  { label: "Forestry", value: "Forestry" },
  { label: "Industrial Processing", value: "Industrial Processing" },
  { label: "Nature Based", value: "Nature Based" },
  { label: "Renewable Energy", value: "Renewable Energy" },
  { label: "Other", value: "Other" },
];

export const countries = [
  { label: "Asia", value: "Asia" },
  { label: "Bolivia", value: "Bolivia" },
  { label: "Brazil", value: "Brazil" },
  { label: "Bulgaria", value: "Bulgaria" },
  { label: "Cambodia", value: "Cambodia" },
  { label: "Canada", value: "Canada" },
  { label: "Chile", value: "Chile" },
  { label: "China", value: "China" },
  { label: "Congo", value: "Congo" },
  { label: "Ecuador", value: "Ecuador" },
  { label: "Guatemala", value: "Guatemala" },
  { label: "India", value: "India" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Kenya", value: "Kenya" },
  { label: "Latin America", value: "Latin America" },
  { label: "Madagascar", value: "Madagascar" },
  { label: "Myanmar", value: "Myanmar" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "Oceania", value: "Oceania" },
  { label: "Pakistan", value: "Pakistan" },
  { label: "South Korea", value: "South Korea" },
  { label: "Thailand", value: "Thailand" },
  { label: "Turkey", value: "Turkey" },
  { label: "Uganda", value: "Uganda" },
  { label: "Uruguay", value: "Uruguay" },
  { label: "Vietnam", value: "Viet Nam" },
];

export const vintages = [
  "1970",
  "2006",
  "2008",
  "2009",
  "2010",
  "2011",
  "2012",
  "2013",
  "2014",
  "2015",
  "2016",
  "2017",
  "2018",
  "2019",
  "2020",
].map((vintage) => ({
  label: vintage,
  value: vintage,
}));

export const mockProjectDetails = [
  {
    id: "0x262174c66306cf03025cb324a31c1eef8e8be9c2",
    tokenAddress: "0x262174c66306cf03025cb324a31c1eef8e8be9c2",
    name: "Renewable Energy Project by LNB Group",
    country: "India",
    region: "Asia",
    vintage: 1577836800,
    methodologyCategory: "Renewable Energy",
    category: "Energy industries (renewable/non-renewable sources)",
    currentSupply: 333,
  },
  {
    id: "0x8a28aed48cbf8d2dad6bb1d173940203d151a1c6",
    tokenAddress: "0x8a28aed48cbf8d2dad6bb1d173940203d151a1c6",
    name: "Hebei Guyuan County Dongxinying 199.5 MW Wind Power Project",
    country: "China",
    region: "Asia",
    vintage: 1546300800,
    methodologyCategory: "Renewable Energy",
    category: "Energy industries (renewable/non-renewable sources)",
    currentSupply: 2,
  },
  {
    id: "0x7dbeebf8c2356ff8c53e41928c9575054a6f331b",
    tokenAddress: "0x7dbeebf8c2356ff8c53e41928c9575054a6f331b",
    name: "Pacajai REDD+ Project",
    country: "Brazil",
    region: "Latin America",
    vintage: 1483228800,
    methodologyCategory: "Forestry",
    category: "Agriculture Forestry and Other Land Use",
    currentSupply: 28903,
  },
  {
    id: "0x4e9b0757b1783384d1d089b00543f324f3a6688c",
    tokenAddress: "0x4e9b0757b1783384d1d089b00543f324f3a6688c",
    name: "Shandong Taipingshan Wind Farm Project",
    country: "China",
    region: "Asia",
    vintage: 1388534400,
    methodologyCategory: "Renewable Energy",
    category: "Energy industries (renewable/non-renewable sources)",
    currentSupply: 16993,
  },
];
