export const filterOptions = {
  bct: {
    types: [
      { label: "Energy Efficiency", value: "Energy Efficiency" },
      { label: "Forestry", value: "Forestry" },
      { label: "Industrial Processing", value: "Industrial Processing" },
      { label: "Renewable Energy", value: "Renewable Energy" },
      { label: "Other", value: "Other" },
    ],
    regions: [
      { label: "Brazil", value: "Brazil" },
      { label: "Chile", value: "Chile" },
      { label: "China", value: "China" },
      { label: "Congo", value: "Congo" },
      { label: "Ecuador", value: "Ecuador" },
      { label: "India", value: "India" },
      { label: "Indonesia", value: "Indonesia" },
      { label: "South Korea", value: "South Korea" },
      { label: "Turkey", value: "Turkey" },
      { label: "Uganda", value: "Uganda" },
      { label: "Vietnam", value: "Viet Nam" },
    ],
    vintages: [
      { label: "2007", value: "2007" },
      { label: "2008", value: "2008" },
      { label: "2009", value: "2009" },
      { label: "2010", value: "2010" },
      { label: "2011", value: "2011" },
      { label: "2012", value: "2012" },
      { label: "2013", value: "2013" },
      { label: "2014", value: "2014" },
      { label: "2015", value: "2015" },
      { label: "2017", value: "2017" },
      { label: "2018", value: "2018" },
      { label: "2019", value: "2019" },
    ],
  },
  nct: {
    types: [{ label: "Forestry", value: "Forestry" }],
    regions: [
      { label: "Africa", value: "Africa" },
      { label: "Asia", value: "Asia" },
      { label: "Brazil", value: "Brazil" },
      { label: "China", value: "China" },
      { label: "Kenya", value: "Kenya" },
      { label: "Latin America", value: "Latin America" },
      { label: "Oceania", value: "Oceania" },
    ],
    vintages: [
      { label: "2011", value: "2011" },
      { label: "2012", value: "2012" },
      { label: "2013", value: "2013" },
      { label: "2014", value: "2014" },
      { label: "2015", value: "2015" },
      { label: "2017", value: "2017" },
      { label: "2019", value: "2019" },
    ],
  },
  ubo: {
    types: [
      { label: "Renewable Energy", value: "Renewable Energy" },
      { label: "Other", value: "Other" },
    ],
    regions: [
      { label: "Asia", value: "Asia" },
      { label: "China", value: "China" },
      { label: "India", value: "India" },
    ],
    vintages: [
      { label: "2014", value: "2014" },
      { label: "2015", value: "2015" },
      { label: "2017", value: "2017" },
      { label: "2019", value: "2019" },
    ],
  },
  nbo: {
    types: [
      { label: "Forestry", value: "Forestry" },
      { label: "Other Nature Based", value: "Other Nature Based" },
    ],
    regions: [
      { label: "Asia", value: "Asia" },
      { label: "Brazil", value: "Brazil" },
      { label: "China", value: "China" },
      { label: "Latin America", value: "Latin America" },
    ],
    vintages: [
      { label: "2014", value: "2014" },
      { label: "2015", value: "2015" },
      { label: "2017", value: "2017" },
      { label: "2018", value: "2018" },
    ],
  },
  mco2: {
    types: [],
    regions: [],
    vintages: [],
  },
};
