export const types = [
  { label: "Agriculture", value: "Agriculture" },
  { label: "Energy Efficiency", value: "Energy Efficiency" },
  { label: "Forestry", value: "Forestry" },
  { label: "Industrial Processing", value: "Industrial Processing" },
  { label: "Nature Based", value: "Nature Based" },
  { label: "Renewable Energy", value: "Renewable Energy" },
  { label: "Other", value: "Other" },
];

export const regions = [
  { label: "Africa", value: "Africa" },
  { label: "Asia", value: "Asia" },
  { label: "Bolivia", value: "Bolivia" },
  { label: "Brazil", value: "Brazil" },
  { label: "Bulgaria", value: "Bulgaria" },
  { label: "Cambodia", value: "Cambodia" },
  { label: "Canada", value: "Canada" },
  { label: "Chile", value: "Chile" },
  { label: "China", value: "China" },
  { label: "Congo", value: "Congo" },
  { label: "Ecuador", value: "Ecuador" },
  { label: "Guatemala", value: "Guatemala" },
  { label: "India", value: "India" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Kenya", value: "Kenya" },
  { label: "Latin America", value: "Latin America" },
  { label: "Madagascar", value: "Madagascar" },
  { label: "Malawi", value: "Malawi" },
  { label: "Myanmar", value: "Myanmar" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "Oceania", value: "Oceania" },
  { label: "Pakistan", value: "Pakistan" },
  { label: "South Korea", value: "South Korea" },
  { label: "Thailand", value: "Thailand" },
  { label: "Turkey", value: "Turkey" },
  { label: "Uganda", value: "Uganda" },
  { label: "Uruguay", value: "Uruguay" },
  { label: "Vietnam", value: "Viet Nam" },
];

export const vintages = [
  "2006",
  "2007",
  "2008",
  "2009",
  "2010",
  "2011",
  "2012",
  "2013",
  "2014",
  "2015",
  "2016",
  "2017",
  "2018",
  "2019",
  "2020",
].map((vintage) => ({
  label: vintage,
  value: vintage,
}));
