import Layout from "components/Layout";
import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(props: {
    children: React.ReactNode;
    verraCreditsChart: JSX.Element;
    tokenizedCreditsChart: JSX.Element;
}) {
    return (
        <html lang="en">
            < body data-theme='theme-light'>
                < Layout > {props.children}</Layout >
            </body >
        </html >
    );
}
