import Layout from "components/Layout";
import { loadTranslation } from "lib/i18n";
import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const locale = props.params.locale;
  const translation = await loadTranslation(locale);
  return (
    <html lang={locale}>
      <body data-theme="theme-light">
        <Layout locale={props.params.locale} translation={translation}>
          {" "}
          {props.children}
        </Layout>
      </body>
    </html>
  );
}
