query getCarbonOffsetsCategories {
  carbonOffsets(first: 1000) {
    methodologyCategory
  }
}

query getCarbonOffsetsCountries {
  carbonOffsets(first: 1000) {
    country
  }
}

query getCarbonOffsetsVintages {
  carbonOffsets(first: 1000) {
    vintageYear
  }
}

query getCarbonOffsetsByProjectAndVintage($key: String!, $vintageStr: String) {
  carbonOffsets(where: { projectID: $key, vintageYear: $vintageStr }) {
    id
    name
    tokenAddress
    vintage
    vintageYear
    bridge
    projectID
    methodology
    methodologyCategory
    country
    category
    name
    registry
    totalBridged
    totalRetired
    currentSupply
    storageMethod
    balanceUBO
    balanceNBO
    balanceNCT
    balanceBCT
  }
}

query findCarbonOffsets(
  $country: [String!]
  $category: [String!]
  $search: String
  $vintage: [String!]
) {
  carbonOffsets(
    first: 1000
    where: {
      and: [
        { methodologyCategory_in: $category }
        { country_in: $country }
        { vintageYear_in: $vintage }
        {
          or: [
            { name_contains_nocase: $search }
            { projectID_contains_nocase: $search }
          ]
        }
      ]
    }
  ) {
    id
    name
    tokenAddress
    vintage
    vintageYear
    bridge
    projectID
    methodology
    methodologyCategory
    country
    category
    name
    registry
    totalBridged
    totalRetired
    storageMethod
    lastUpdate
    balanceUBO
    balanceNBO
    balanceNCT
    balanceBCT
  }
}
