import { REGISTRIES } from "./registries.constants";

export const URLS = {
  app: "https://app.klimadao.finance",
  blog: "https://klimadao.medium.com",
  bonds: "https://app.klimadao.finance/#/bonds",
  buy: "https://www.klimadao.finance/buy",
  carbonDashboard: "https://carbon.klimadao.finance",
  carbonmark: "https://www.carbonmark.com",
  carbonmarkContactForm:
    "https://share-eu1.hsforms.com/1RWJWvyrHT1C_an4cZOHH3gfhhlr",
  carbonmarkEmail: "mailto:support@carbonmark.com",
  coinbase: "https://www.coinbase.com/",
  community: "https://www.klimadao.finance/community",
  communityHub: "https://klimadao.notion.site",
  contact: "https://www.klimadao.finance/contact",
  creolBusinessCalculator: "https://klima.creol.io/#/office",
  creolIndividualCalculator: "https://klima.creol.io/#/footprint",
  cryptoOffsetCalculator: "https://carbon.fyi/",
  defaultEthRpc: "https://cloudflare-eth.com",
  discordContributorsInvite: "https://discord.gg/uWvjTuZ65v",
  discordInvite: "https://discord.com/invite/klimadao",
  emailSignUp:
    "https://docs.google.com/forms/d/e/1FAIpQLScw_YKuWZJePkM8lh6VVOwtpYToi1FpfgYgxLeBuIMa2ewyuA/viewform",
  epaSource:
    "https://www.epa.gov/energy/greenhouse-gases-equivalencies-calculator-calculations-and-references",
  forum: "https://forum.klimadao.finance",
  gitbook: "https://klima-dao.gitbook.io/klima-dao",
  github: "https://github.com/KlimaDAO",
  goldStandardProjectDetailPage: `${REGISTRIES.GoldStandard.url}/projects/details`,
  home: "https://www.klimadao.finance",
  infinity: "https://www.klimadao.finance/infinity",
  info: "https://app.klimadao.finance/info",
  infuraEthRpc: "https://mainnet.infura.io/v3",
  infuraMumbaiRpc: "https://polygon-mumbai.infura.io/v3",
  infuraPolygonRpc: "https://polygon-mainnet.infura.io/v3",
  klimaInfinityContactForm:
    "https://share-eu1.hsforms.com/1g2uooleDQ06MaRpylL5irwfhhlr",
  lifiOffset:
    "https://transferto.xyz/showcase/carbon-offset?fromChain=eth&toChain=pol&toToken=0x2791bca1f2de4661ed88a30c99a7a9449aa84174",
  lifiStake:
    "https://transferto.xyz/showcase/etherspot-klima?fromChain=eth&toChain=pol&toToken=0x2791bca1f2de4661ed88a30c99a7a9449aa84174",
  linkedIn: "https://www.linkedin.com/company/klimadao/",
  linkedInCarbonmark: "https://www.linkedin.com/company/carbonmarkcom",
  loveletter: "https://loveletter.klimadao.finance",
  marketplace: "https://www.carbonmark.com/projects",
  mediaImage: "https://www.klimadao.finance/og-media.png",
  mediaRequestForm:
    "https://share-eu1.hsforms.com/1ILV2ALyPSqqUAeLdstfZZgfhhlr",
  moonpayMatic: "https://www.moonpay.com/buy/matic",
  officialDocs: "https://docs.klimadao.finance",
  offset: "https://app.klimadao.finance/#/offset",
  partnerShipsContactForm:
    "https://share-eu1.hsforms.com/1fEb0LUdcRlKGTzNCVYz6igfhhlr",
  pledges: "https://www.klimadao.finance/pledge",
  podcast: "https://rss.com/podcasts/potk",
  polygonBridge: "https://wallet.polygon.technology/polygon/bridge/deposit",
  polygonMainnetRpc: "https://polygon-rpc.com",
  polygonTestnetRpc: "https://rpc-mumbai.maticvigil.com",
  polygonTor: "https://polygon.tor.us/",
  polygonscan: "https://polygonscan.com",
  polyscanGasStation: "https://gasstation-mainnet.matic.network/v2",
  portfolio: "https://www.carbonmark.com/portfolio",
  pressEmail: "mailto:press@klimadao.finance",
  reddit: "https://www.reddit.com/r/Klima",
  redeem: "https://app.klimadao.finance/#/redeem",
  resources: "https://www.klimadao.finance/resources",
  resourcesCarbonmark: "https://www.carbonmark.com/resources",
  retirements: "https://www.klimadao.finance/retirements",
  siteBlog: "https://www.klimadao.finance/blog",
  snapshot: "https://snapshot.org/#/klimadao.eth",
  stake: "https://app.klimadao.finance/#/stake",
  sushiSwap: "https://www.sushi.com/swap",
  telegram: "https://t.me/joinchat/Zb06f_mnMosyYTYy",
  transakMatic:
    "https://global.transak.com/?fiatCurrency=EUR&network=polygon&cryptoCurrencyCode=MATIC",
  tutorial:
    "https://klimadao.notion.site/I-m-new-to-Klima-How-do-I-participate-c28426c5100244788f791f62e375ffcc",
  twitter: "https://twitter.com/KlimaDAO",
  twitterCarbonmark: "https://twitter.com/carbonmarkcom",
  veraProjectSearch: `${REGISTRIES.Verra.api}/resource/resource/search?maxResults=2000&$count=true&$skip=0&$top=50`,
  veraProjectDetailPage: `${REGISTRIES.Verra.url}/app/projectDetail/VCS`, // add ID after VCS like /191
  wrap: "https://app.klimadao.finance/#/wrap",
  youtube: "https://www.youtube.com/c/klimadaofinance",
};
