query getCarbonOffsetsCategories {
  carbonOffsets {
    methodologyCategory
  }
}

query getCarbonOffsetsCountries {
  carbonOffsets {
    country
  }
}

query getCarbonOffsetsVintages {
  carbonOffsets {
    vintageYear
  }
}
