name: "Carbonmark Status Check"
description: "Checks the status of a commit, branch or tag and outputs the result"
author: "Carbonmark"
inputs:
  GH_TOKEN:
    required: true
    description: "The default GITHUB_TOKEN"
  ref:
    required: false
    description: "The ref can be a specific commit SHA, a branch name or a tag name"
    default: ${{ github.sha }}
  timeoutSeconds:
    description: "The number of seconds to wait for the check to complete."
    default: 1200
  intervalSeconds:
    description: "The number of seconds to wait before each poll of the GitHub Status API."
    default: 10

outputs:
  status: # id of the output
    description: "Status can be 'failed' or 'success'"
runs:
  using: "node16"
  main: "dist/index.js"
