fragment CMSProjectFragment on Project {
  country
  description
  id: _id
  geolocation {
    lat
    lng
    alt
  }
  methodologies {
    id: _id
    category
    name
  }
  name
  region
  registry
  url
  registryProjectId
  externalMedia {
    uri
    description
  }
}

fragment CMSProjectContentFragment on ProjectContent {
  project {
    registry
    registryProjectId
  }
  shortDescription
  longDescription
  coverImage {
    asset {
      url
    }
  }
  images {
    asset {
      url
      label
      title
      altText
    }
  }
}
