# Write your query or mutation here
query getCMSProject($registry: String!, $registryProjectId: String!) {
  allProject(
    where: {
      registry: { eq: $registry }
      registryProjectId: { eq: $registryProjectId }
    }
  ) {
    ...CMSProjectFragment
  }
}

query getCMSProjectContent($registry: String!, $registryProjectId: String!) {
  allProjectContent(
    where: {
      project: {
        registryProjectId: { eq: $registryProjectId }
        registry: { eq: $registry }
      }
    }
  ) {
    ...CMSProjectContentFragment
  }
}

query getAllCMSProjects {
  allProject {
    ...CMSProjectFragment
  }
}

query getAllCMSProjectContent {
  allProjectContent {
    ...CMSProjectContentFragment
  }
}
