fragment ProvenanceRecordFragment on ProvenanceRecord {
  id
  transactionType
  registrySerialNumbers
  token
  sender
  receiver
  originalAmount
  remainingAmount
  createdAt
  updatedAt
}

fragment carbonCreditFragment on CarbonCredit {
  id
  bridgeProtocol
  vintage
  currentSupply
  retired
  crossChainSupply
}

fragment retireFragment on Retire {
  id
  bridgeID
  amount
  beneficiaryAddress {
    id
  }
  beneficiaryName
  retirementMessage
  retiringAddress {
    id
  }
  retiringName
  timestamp
}
