fragment ProvenanceRecordFragment on ProvenanceRecord {
  id
  transactionType
  registrySerialNumbers
  token
  sender
  receiver
  originalAmount
  remainingAmount
  createdAt
  updatedAt
}

fragment RetireFragment on Retire {
  id
  bridgeID
  hash
  amount
  pool {
    id
  }
  beneficiaryAddress {
    id
  }
  beneficiaryName
  retirementMessage
  retiringAddress {
    id
  }
  retiringName
  timestamp
}

fragment DigitalCarbonProjectFragment on CarbonProject {
  id
  name
  projectID
  methodologies
  country
  category
  registry
  region
}

fragment CarbonCreditFragment on CarbonCredit {
  vintage
  currentSupply
  id
  crossChainSupply
  bridgeProtocol
  bridged
  retired
  project {
    id
  }
}

fragment PoolBalancesFragment on CarbonPoolCreditBalance {
  balance
  id
  deposited
  redeemed
  pool {
    name
    supply
    id
    decimals
    dailySnapshots {
      lastUpdateTimestamp
    }
  }
}

fragment PoolFragment on CarbonPool {
  name
  supply
  id
  decimals
  dailySnapshots {
    lastUpdateTimestamp
  }
}
