query getProjectCredits($projectID: String!, $vintage: Int) {
  carbonProjects(where: { projectID: $projectID }) {
    registry
    region
    projectID
    name
    methodologies
    id
    country
    category
    carbonCredits(where: { vintage: $vintage }) {
      vintage
      currentSupply
      poolBalances {
        balance
        id
        deposited
        redeemed
        pool {
          name
          supply
          id
          decimals
        }
      }
      id
      crossChainSupply
      bridgeProtocol
      bridged
      retired
    }
  }
}

query getProvenanceRecords($id: [Bytes!]) {
  provenanceRecords(where: { id_in: $id }) {
    ...ProvenanceRecordFragment
    priorRecords(orderBy: createdAt, orderDirection: desc) {
      ...ProvenanceRecordFragment
    }
  }
}
