query getProjectCredits($projectID: String!, $vintage: Int) {
  carbonProjects(where: { projectID: $projectID }) {
    registry
    region
    projectID
    name
    methodologies
    id
    country
    category
    carbonCredits(where: { vintage: $vintage }) {
      vintage
      currentSupply
      poolBalances {
        balance
        id
        deposited
        redeemed
        pool {
          name
          supply
          id
          decimals
        }
      }
      id
      crossChainSupply
      bridgeProtocol
      bridged
      retired
    }
  }
}

query getKlimaRetirement($id: ID!) {
  klimaRetire(id: $id) {
    retire {
      ...retireFragment
      credit {
        ...carbonCreditFragment
      }
    }
  }
}

query getProvenanceRecords($hash: [Bytes!]) {
  provenanceRecords(where: { transactionHash_in: $hash }) {
    ...ProvenanceRecordFragment
    priorRecords(orderBy: createdAt, orderDirection: desc) {
      ...ProvenanceRecordFragment
    }
  }
}
