# @todo these "first:1000" will possibly miss results if there are more than 1000
# this will cause a silent error. GQL Resolver needs to be updated to allow null search params
# to return all possible values
query getCategories {
  categories(first: 1000) {
    id
  }
}

query getCountries {
  countries(first: 1000) {
    id
  }
}

query getVintages {
  projects(first: 1000) {
    vintage
  }
}

query getPurchaseById($id: ID!) {
  purchase(id: $id) {
    id
    amount
    listing {
      id
      project {
        key
        vintage
      }
    }
    price
  }
}

query getUserByWallet($wallet: Bytes, $expiresAfter: BigInt) {
  users(where: { id: $wallet }) {
    listings(where: { expiration_gt: $expiresAfter }) {
      ...ListingFragment
    }
    activities(orderBy: timeStamp, orderDirection: desc, first: 10) {
      ...ActivityFragment
    }
  }
}

query getProjects($search: String, $vintage: [BigInt!], $expiresAfter: BigInt) {
  projects(where: { name_contains_nocase: $search, vintage_in: $vintage }) {
    ...ProjectFragment
    listings(where: { expiration_gt: $expiresAfter }) {
      ...ListingFragment
    }
  }
}

query getProjectById($projectId: ID!, $expiresAfter: BigInt) {
  project(id: $projectId) {
    ...ProjectFragment
    listings(where: { expiration_gt: $expiresAfter }) {
      ...ListingFragment
    }
    activities {
      ...ActivityFragment
    }
  }
}
