# @todo these "first:1000" will possibly miss results if there are more than 1000
# this will cause a silent error. GQL Resolver needs to be updated to allow null search params
# to return all possible values
query getCategories {
  categories(first: 1000) {
    id
  }
}

query getCountries {
  countries(first: 1000) {
    id
  }
}

query getVintages {
  projects(first: 1000) {
    vintage
  }
}

query getPurchaseById($id: ID!) {
  purchase(id: $id) {
    amount
    id
    listing {
      id
      project {
        ...ProjectFragment
      }
      seller {
        id
      }
      tokenAddress
    }
    price
  }
}

query getUserByWallet(
  $wallet: String
  $expiresAfter: BigInt
  $minSupply: BigInt
) {
  listings(
    where: {
      seller: $wallet
      expiration_gt: $expiresAfter
      leftToSell_gt: $minSupply
    }
  ) {
    ...ListingFragment
  }
  activities(
    orderBy: timeStamp
    orderDirection: desc
    first: 10
    where: {
      or: [{ seller: $wallet, activityType_not: Purchase }, { buyer: $wallet }]
    }
  ) {
    ...ActivityFragment
  }
}

query getProjects(
  $search: String
  $country: [String!]
  $category: [String!]
  $vintage: [BigInt!]
  $expiresAfter: BigInt
  $minSupply: BigInt
) {
  projects(
    where: {
      and: [
        {
          or: [
            { name_contains_nocase: $search }
            { key_contains_nocase: $search }
          ]
        }
        { country_in: $country }
        { category_in: $category }
        { vintage_in: $vintage }
      ]
    }
  ) {
    ...ProjectFragment
    listings(
      where: { expiration_gt: $expiresAfter, leftToSell_gt: $minSupply }
    ) {
      ...ListingFragment
    }
  }
}

query getProjectById(
  $projectId: ID!
  $expiresAfter: BigInt
  $minSupply: BigInt
) {
  project(id: $projectId) {
    ...ProjectFragment
    listings(
      where: { expiration_gt: $expiresAfter, leftToSell_gt: $minSupply }
    ) {
      ...ListingFragment
    }
  }
}

query getActivitiesByProjectId(
  $projectId: [ID!]
  $activityType: [ActivityType!]
) {
  activities(
    where: { project_: { id_in: $projectId }, activityType_in: $activityType }
  ) {
    ...ActivityFragment
  }
}

query getAllActivities($activityType: [ActivityType!]) {
  activities(where: { activityType_in: $activityType }) {
    ...ActivityFragment
  }
}
