query getCreditListings($projectId: String, $vintageStr: BigInt) {
  projects(where: { key: $projectId, vintage: $vintageStr }) {
    id
    listings {
      createdAt
      updatedAt
      id
      totalAmountToSell
      leftToSell
      tokenAddress
      active
      deleted
      singleUnitPrice
      seller {
        id
      }
    }
    activities {
      id
      timeStamp
      activityType
      price
      previousPrice
      amount
      previousAmount
      buyer {
        id
      }
      seller {
        id
      }
    }
  }
}

query getPurchasesById($id: Bytes) {
  purchases(first: 1, where: { id: $id }) {
    id
    amount
    user {
      id
    }
    listing {
      id
      seller {
        id
      }
      project {
        key
        vintage
      }
    }
    price
  }
}

query getUserByWallet($wallet: Bytes) {
  users(where: { id: $wallet }) {
    listings {
      id
      totalAmountToSell
      leftToSell
      tokenAddress
      active
      deleted
      batches
      batchPrices
      singleUnitPrice
      createdAt
      updatedAt
      seller {
        id
      }
    }
    activities(orderBy: timeStamp, orderDirection: desc, first: 10) {
      id
      amount
      previousAmount
      price
      previousPrice
      timeStamp
      activityType
      project {
        key
        vintage
      }
      buyer {
        id
      }
      seller {
        id
      }
    }
  }
}
