# @todo these "first:1000" will possibly miss results if there are more than 1000
# this will cause a silent error. GQL Resolver needs to be updated to allow null search params
# to return all possible values
query getCategories {
  categories(first: 1000) {
    id
  }
}

query getCountries {
  countries(first: 1000) {
    id
  }
}

query getVintages {
  projects(first: 1000) {
    vintage
  }
}

query getPurchasesById($id: Bytes) {
  purchases(first: 1, where: { id: $id }) {
    id
    amount
    listing {
      id
      project {
        key
        vintage
      }
    }
    price
  }
}

query getUserByWallet($wallet: Bytes, $expiresAfter: BigInt) {
  users(where: { id: $wallet }) {
    listings(where: { expiration_gt: $expiresAfter }) {
      ...ListingFragment
    }
    activities(orderBy: timeStamp, orderDirection: desc, first: 10) {
      ...ActivityFragment
    }
  }
}

query findProjects(
  $country: [String!]
  $category: [String!]
  $search: String
  $vintage: [BigInt!]
) {
  projects(
    where: {
      category_: { id_in: $category }
      country_: { id_in: $country }
      name_contains_nocase: $search
      vintage_in: $vintage
    }
  ) {
    ...ProjectFragment
    listings {
      ...ListingFragment
    }
  }
}

query getCreditListings($projectId: String, $vintageStr: BigInt) {
  projects(where: { key: $projectId, vintage: $vintageStr }) {
    id
    listings {
      ...ListingFragment
    }
    activities {
      ...ActivityFragment
    }
  }
}
