fragment ListingFragment on Listing {
  id
  totalAmountToSell
  leftToSell
  tokenAddress
  active
  deleted
  singleUnitPrice
  createdAt
  updatedAt
  seller {
    id
  }
  project {
    ...ProjectFragment
  }
  expiration
  minFillAmount
  tokenId
}

fragment ProjectFragment on Project {
  id
  key
  vintage
  name
  category {
    id
  }
  country {
    id
  }
  methodology
}

fragment ActivityFragment on Activity {
  id
  amount
  previousAmount
  price
  previousPrice
  timeStamp
  activityType
  project {
    key
    vintage
  }
  buyer {
    id
  }
  seller {
    id
  }
}

fragment PurchaseFragment on Purchase {
  amount
  id
  listing {
    id
    project {
      ...ProjectFragment
    }
    seller {
      id
    }
    tokenAddress
  }
  price
}
