fragment ListingFragment on Listing {
  id
  totalAmountToSell
  leftToSell
  tokenAddress
  active
  deleted
  singleUnitPrice
  createdAt
  updatedAt
  seller {
    id
  }
  project {
    ...ProjectFragment
  }
  expiration
  minFillAmount
}

fragment ProjectFragment on Project {
  id
  key
  projectID
  name
  vintage
  projectAddress
  registry
  methodology
  projectType
  region
  category {
    id
  }
}

fragment ActivityFragment on Activity {
  id
  amount
  previousAmount
  price
  previousPrice
  timeStamp
  activityType
  project {
    key
    vintage
  }
  buyer {
    id
  }
  seller {
    id
  }
}
