export const VERRA_PROJECT_NAMES = [
  ['VCS-476', '28MW Jinkouba Hydropower Project', 'China'],
  ['VCS-1715', 'Inner Mongolia Wu‘erqihan IFM (conversion of logged to protected forest) Project', 'China'],
  [
    'VCS-309',
    'Bundled grid-connected wind electricity generation project identified as Bundle E3 in Maharashtra and Gujarat, India',
    'India',
  ],
  ['VCS-584', '2.5 MW Rice husk based cogeneration plant at Hanuman Agro Industries Limited', 'India'],
  ['VCS-1094', 'Ecomapua Amazon REDD Project', 'Brazil'],
  ['VCS-817', 'Datong River Zhuchaxia Hydropower Station', 'China'],
  ['VCS-728', 'CECIC Gansu Yumen Changma No.3 Wind Farm Project', 'China'],
  [
    'VCS-1764',
    'Reforestation and Restoration of degraded mangrove lands, sustainable livelihood and community development in Myanmar',
    'Myanmar',
  ],
  ['VCS-191', '4×50 MW Dayingjiang- 3 Hydropower Project Phases 1&2', 'China'],
  ['VCS-766', 'Teesta- V Hydro Power project in Sikkim', 'India'],
  ['VCS-148', 'Hebei Kangbao Wolongtushan 30 MW Wind Farm Project', 'China'],
  ['VCS-1824', 'Liucheng Biomass Power Generation Project in Guangxi Zhuang Autonomous Region, China', 'China'],
  ['VCS-192', '48 MW Houqiao Hydropower Project, Yunnan, China', 'China'],
  [
    'VCS-68',
    '119.8 MW Natural Gas based Combined Cycle Power Plant, at Tanjavur, Tamilnadu by M/s Aban  Power Company Limited',
    'India',
  ],
  ['VCS-494', 'Zhangjiagang Nature Gas Power Generation Project', 'China'],
  ['VCS-486', '50 MW Sipansihaporas Hydro Power Plant, North Sumatra', 'Indonesia'],
  ['VCS-1143', 'Ningxia Angli Lingwu Photovoltaic Grid Connected Power Plant Project', 'China'],
  ['VCS-1037', 'Guazhou Beidaqiao No.1 Wind Farm Project in Gansu Province, China', 'China'],
  ['VCS-2098', 'Nanhai MSW Incineration II Project', 'China'],
  [
    'VCS-929',
    'Energy Efficiency and Solid Waste Diversion Activities within the Quebec Sustainable Community',
    'Canada',
  ],
  ['VCS-1140', 'Henan Xinxiang 24MW Biomass based Cogeneration Project', 'China'],
  ['VCS-1205', 'Tatar Hydro Electricity Power Plant', 'Turkey'],
  ['VCS-1174', 'Akcay 28.78 MW, Hydroelectric Power Plant Project (HEPP), Turkey', 'Turkey'],
  ['VCS-1221', 'Eglence I-II Hydroelectric Power Plant', 'Turkey'],
  ['VCS-253', 'Fuzhou Hongmiaoling Landfill  Gas to Electricity Project', 'China'],
  [
    'VCS-499',
    'Positive Climate Care 4.67 MW Bundled Grid connected Wind Power Project Activity in Jaisalmer, Rajasthan, India',
    'India',
  ],
  ['VCS-498', 'Grid-connected wind electricity generation project in Tamil Nadu, India', 'India'],
  ['VCS-338', 'Methane Recovery Project Praktijkcentrum Sterksel, North Brabant, The Netherlands', 'Netherlands'],
  ['VCS-1189', 'Shandong Taipingshan Wind Farm Project', 'China'],
  ['VCS-51', '29.70 MW Wind Power project in Karnataka India', 'India'],
  ['VCS-708', 'Engenheiro Ernesto Jorge Dreher and Engenheiro Henrique Kotzian SHPs VCS Project (JUN1120)', 'Brazil'],
  ['VCS-982', 'Combined cycle natural gas based grid connected power plant at Jegurupadu, India', 'India'],
  ['VCS-1188', 'Shandong Wendeng Zhangjiachan Wind Farm Project', 'China'],
  ['VCS-493', '5 MW Brahm Ganga Hydro – Electric Project at Kullu district of Himachal Pradesh, India', 'India'],
  ['VCS-535', '78 MW AKOCAK Hydroelectric Power Plant', 'Turkey'],
  ['VCS-1718', 'Inner Mongolia Keyihe IFM (conversion of logged to protected forest) Project', 'China'],
  ['VCS-12', 'Chuanwei Group 24 MW Waste Gas based Captive Power Plant', 'China'],
  ['VCS-414', 'Hebei Haixing 49.5MW Wind Farm Project', 'China'],
  ['VCS-823', 'Datong River Tianwanggou Hydropower Station', 'China'],
  ['VCS-173', 'Vishnuprayag Hydro-electric Project (VHEP) by Jaiprakash Power Ventures Ltd.(JPVL)', 'India'],
  ['VCS-875', 'FLORESTAL SANTA MARIA PROJECT', 'Brazil'],
  ['VCS-292', '150 MW grid connected Wind Power based electricity generation project in Gujarat, India.', 'India'],
  ['VCS-1566', 'REDD+ Project Resguardo Indigena Unificado Selva de Mataven (RIU SM)', 'Colombia'],
  ['VCS-812', 'Bull Run Overseas Forest Carbon Project', 'Belize'],
  ['VCS-1258', 'Saint Nikola Wind Farm', 'Bulgaria'],
  ['VCS-1100', 'SANIBEY DAM AND HYDROELECTRIC POWER PLANT', 'Turkey'],
  ['VCS-830', 'Beijing Guanting Wind Power Project Phase II and Phase II addition', 'China'],
  ['VCS-631', '13.25 MW Wind Power Generation by RMTL, in Kutch, Gujarat', 'India'],
  ['VCS-655', '24.8 MW Wind power project by Belgaum Wind Farms Private Ltd. in Gadag, Karnataka', 'India'],
  ['VCS-1182', 'CGN Inner Mongolia Zhurihe Phase I Wind Farm Project', 'China'],
  ['VCS-1052', 'North Pikounda REDD+', 'Congo'],
  ['VCS-274', 'Hanuman Ganga Hydro (4.95 MW) Plant at Uttarakhand', 'India'],
  ['VCS-1186', 'Viñales biomass power plant', 'Chile'],
  ['VCS-773', '8MW Waste Heat Recovery Based Power Project by Sree Rengaraaj Power India Private Limited', 'India'],
  ['VCS-1382', 'The Envira Amazonia Project - A Tropical Forest Conservation Project in Acre, Brazil', 'Brazil'],
  ['VCS-921', 'Inner Mongolia Jingneng Saihan Wind Farm Phase II Project', 'China'],
  ['VCS-1203', 'Suzlon 8.40 MW Wind Power Project', 'India'],
  ['VCS-1693', 'Wind Power Project in Maharashtra State, India', 'India'],
  ['VCS-1162', "Jiangxi Province Le'an County Forest Farm Carbon Sink Project", 'China'],
  ['VCS-905', 'The Yokuslu- Kalkandere Hydroelectric Power Plant', 'Turkey'],
  ['VCS-753', 'The Cevizlik Run-of-River Hydroelectric Power Plant', 'Turkey'],
  ['VCS-981', 'Pacajai REDD+ Project', 'Brazil'],
  ['VCS-1291', 'Hydro Power Project in backward district of Andhra Pradesh, India', 'India'],
  ['VCS-669', 'Wind Energy project by Ramco group in india', 'India'],
  ['VCS-786', 'Hyundai Steel Waste Energy Cogeneration Project', 'South Korea'],
  ['VCS-1146', 'The Hyundai Waste Energy Recovery CO-Generation Project Phase II', 'South Korea'],
  ['VCS-917', 'ASLANCIK HYDRO POWER PLANT PROJECT', 'Turkey'],
  ['VCS-1121', 'Anhui Guzhen Biomass Generation Project', 'China'],
  ['VCS-2097', 'Tepekisla Dam & Hydropower Plant Project', 'Turkey'],
  ['VCS-1985', '100 MW Bundled Wind Power Project in Anantapuram, Andhra Pradesh', 'India'],
  [
    'VCS-614',
    'Chemical Recovery Project at Satia Industries Ltd. (SIL), formerly known as Satia Paper Mills Limited Village Rupana, Punjab',
    'India',
  ],
  ['VCS-832', 'Cikel Brazilian Amazon REDD APD Project   Avoiding Planned Deforestation', 'Brazil'],
  ['VCS-1427', 'Adiguzel II Hydroelectric Power Plant', 'Turkey'],
  ['VCS-1578', '15 MW Solar Photovoltaic Power Project at Gujarat', 'India'],
  [
    'VCS-566',
    '10 MW Wind Power Project in Maharashtra by Deepak Fertilizers and Petrochemicals Corporation Limited',
    'India',
  ],
  [
    'VCS-265',
    '4.5 MW Grouped Small Hydropower Projects for Grid system by Bhoruka Power Corporation Limited in Karnataka State, India.',
    'India',
  ],
  ['VCS-836', 'Song Ong Hydropower Project', 'Viet Nam'],
  ['VCS-927', '13.75 MW wind power project in Davangere, Karnataka, India', 'India'],
  ['VCS-1654', 'Fortaleza Ituxi REDD Project', 'Brazil'],
  ['VCS-132', '9 MW Neria Hyrdroelectric project, Karnataka, India', 'India'],
  ['VCS-1580', 'Solar Grouped project by ACME Group (EKIESL-VCS-Aug-16-01)', 'India'],
  ['VCS-1160', '6.5 MW cogeneration project in Akbarpur, Punjab', 'India'],
  ['VCS-1166', 'Nanba Associated Gas Processing Plant and the Auxiliary Engineering', 'China'],
  ['VCS-1547', '5MW Biomass Based Cogeneration Project at Sainsons', 'India'],
  ['VCS-1762', 'Bundled Solar Power Project by Solararise India Projects PVT. LTD.', 'India'],
  ['VCS-2092', 'Kirazlık Hydroelectric  Power Plant Project', 'Turkey'],
  ['VCS-896', 'Foz do Chapecó Project', 'Brazil'],
  ['VCS-10', 'BAESA Project', 'Brazil'],
  ['VCS-487', '210 MW Musi Hydro Power Plant, Bengkulu', 'Indonesia'],
  ['VCS-1792', 'Ghani Solar Renewable Power Project by Greenko Group', 'India'],
  ['VCS-1021', 'Grid Connected Wind Power Project by M/s. D. J. Malpani in Rajasthan', 'India'],
  ['VCS-1529', 'Inner Mongolia Chao’er Improved Forest Management Project', 'China'],
  ['VCS-1577', 'Fujian Yong’an Improved Forest Management Project', 'China'],
  ['VCS-810', 'CEYHAN 61.7 MW Hydropower Project', 'Turkey'],
  ['VCS-1758', 'Dereli Hydroelectric Power  Plant', 'Turkey'],
  ['VCS-513', 'Salto Pilão Hydropower Plant Project Activity', 'Brazil'],
  ['VCS-2307', 'Ambatolampy 20 MW solar PV', 'Madagascar'],
  ['VCS-850', 'Inner Mongolia Jingneng Saihan Wind Farm Phase I Project', 'China'],
  ['VCS-1214', 'Vajrakarur Wind Power Project in Andhra Pradesh', 'India'],
  ['VCS-1195', 'Wind Power Project in Rajasthan', 'India'],
  ['VCS-2095', 'Duzce Aksu Hydro Electricity Power Plant', 'Turkey'],
  ['VCS-2026', 'Allain Duhangan Hydroelectric Project (ADHP)', 'India'],
  ['VCS-736', 'Guyuan Wuhuaping 49.5 MW Wind Power Project', 'China'],
  ['VCS-849', 'Inner Mongolia Ximeng Zheligentu Wind Farm Phase I Project', 'China'],
  [
    'VCS-762',
    'Grid connected electricity generation from renewable sources: Uzuncayir 82.0 MW Hydroelectric Power Plant Project, Turkey',
    'Turkey',
  ],
  ['VCS-1345', 'Boyabat Hydroelectric Power Plant', 'Turkey'],
  ['VCS-1935', 'Hubei Hongshan IFM (Conversion of Logged to Protected Forest) Project', 'China'],
  ['VCS-1464', 'Alkumru Hydroelectric Power Plant', 'Turkey'],
  ['VCS-1650', 'Reduced Emissions from Deforestation and Degradation in Keo Seima Wildlife Sanctuary', 'Cambodia'],
  ['VCS-1506', 'Cirakdami Hydro Electricity Power Plant', 'Turkey'],
  [
    'VCS-837',
    'Natural Gas Based Combined Cycle Power Generation, at Kothapeta, East Godavari, Andhra Pradesh, India',
    'India',
  ],
  ['VCS-1748', 'Southern Cardamom REDD+ Project', 'Cambodia'],
  ['VCS-713', 'KOYULHISAR HYDRO ELECTRICITY POWER PLANT', 'Turkey'],
  ['VCS-1499', 'Toros Hydroelectric Power Plant', 'Turkey'],
  ['VCS-1525', 'Wind power project at Jaibhim by SIIL', 'India'],
  ['VCS-1261', 'Grid connected electricity generation using natural gas by Lanco Kondapalli Power Limited', 'India'],
  ['VCS-844', 'Madre de Dios Amazon REDD+ Project', 'Peru'],
  ['VCS-1721', 'ONIL Stoves  Guatemala Uspantan', 'Guatemala'],
  ['VCS-788', 'China Guangdong Shenzhen Qianwan LNG generation project', 'China'],
  ['VCS-426', 'Wastewater Treatment with Biogas System in Palm Oil Mill at Sawi, Chumporn,Thailand', 'Thailand'],
  ['VCS-653', '65MW Dagushan hydropower Project in China', 'China'],
  ['VCS-674', 'Rimba Raya Biodiversity Reserve Project', 'Indonesia'],
  ['VCS-612', 'The Kasigau Corridor REDD Project - Phase II The Community Ranches', 'Kenya'],
  ['VCS-1686', 'Agrocortex REDD Project', 'Brazil'],
  ['VCS-1549', 'AAC Block Project By Aerocon Buildwell Pvt. Ltd. (EKIESL- June 2016-02)', 'India'],
  ['VCS-391', 'Gullubag 96 MW Hydro Electric Power Plant Project, Turkey', 'Turkey'],
  ['VCS-1497', 'VCS Grouped Project for Renewable Power Generation by Essel Mining & Industries Limited', 'India'],
  ['VCS-722', 'Guangdong Huizhou LNG Power Generation Project', 'China'],
  ['VCS-960', 'Lumin/Eucapine Uruguay Forest Plantations on degraded grasslands under extensive grazing', 'Uruguay'],
  ['VCS-876', 'Shree Nakoda Ispat Ltd 12MW Biomass power generation project', 'India'],
  ['VCS-92', '300MW Hydropower project by JHPL', 'India'],
  ['VCS-682', 'Wind Power Project at Anthiyur, Tamil Nadu', 'India'],
  ['VCS-1002', 'Natural Gas based grid connected power project at Peddapuram, A.P. by Gautami Power Limited', 'India'],
  ['VCS-1418', 'Renewable Energy Project by LNB Group', 'India'],
  ['VCS-892', 'Hebei Chengde Weichang Yudaokou Pasture 150MW Wind Farm Project', 'China'],
  ['VCS-2089', 'Rio Taquesi Hydroelectric Power Project', 'Bolivia'],
  ['VCS-1310', 'Guohua Tongliao Kezuo Zhongqi Phase I 49.5 MW Wind Farm Project', 'China'],
  ['VCS-903', 'Hebei Guyuan County Dongxinying 199.5 MW Wind Power Project', 'China'],
  ['VCS-1301', 'Guohua  Rongcheng Phase ll Wind Farm Project', 'China'],
  ['VCS-1542', 'Yunnan Kunming Liangqu Improved Forest Management Project', 'China'],
  ['VCS-1204', 'Guohua Wulate Zhongqi Phase I 49.5 MW Wind farm Project', 'China'],
  ['VCS-1671', 'Wind based power generation by Panama Wind Energy Private Limited in Maharashtra, India', 'India'],
  ['VCS-674', 'Rimba Raya Biodiversity Reserve Project', 'Indonesia'],
  ['VCS-1356', 'Jiangsu Dongtai Phase II Wind Power Project', 'China'],
  ['VCS-986', 'Kumköy Hydroelectric Power Plant, Samsun', 'Turkey'],
  ['VCS-1521', 'Wind Based Power Generation by Mytrah Energy (India) Limited (EKIESL-VCS-January-16-01)', 'India'],
  ['VCS-1190', 'Wind power project in Gujarat', 'India'],
  ['VCS-1883', 'Pichacay Landfill Gas Renewable Energy Project', 'Ecuador'],
  ['VCS-1742', 'Hydroelectric Project in Kinnaur District in Himachal Pradesh', 'India'],
  ['VCS-1768', '216 MWac Kamuthi Solar Power Project', 'India'],
  ['VCS-1781', 'MRMPL Wind Power Project', 'India'],
  ['VCS-1477', 'Katingan Peatland Restoration and Conservation Project', 'Indonesia'],
  ['VCS-985', 'Cordillera Azul National Park REDD Project', 'Peru'],
  ['VCS-934', 'The Mai Ndombe REDD+ Project', 'Congo, The Democratic Republic of The'],
  ['VCS-1187', 'Shandong Yishui Tangwangshan Wind Farm Project', 'China'],
  ['VCS-1656', 'Zhangbei Manjing Windfarm Project', 'China'],
  ['VCS-1508', 'Pakarab Fertiliser Co-generation Power Project', 'Pakistan'],
  ['VCS-1505', 'Bujagali Hydropower Project', 'Uganda'],
  ['VCS-251', 'Biomass Based Cogeneration Project at Nectar Life Sciences Ltd', 'India'],
  ['VCS-733', 'Biomass based steam generation project by Gujarat Ambuja Exports Ltd.', 'India'],
  ['VCS-529', 'Jilin Rice Husk Thermal Energy Generation Project', 'China'],
  ['VCS-528', 'Panjin Rice Husk Thermal Energy Generation Project', 'China'],
  ['VCS-758', 'Saracbendi HPP Run-of-River Hydro Project', 'Turkey'],
  ['VCS-1228', 'El Panul', 'Chile'],
  ['VCS-603', 'Sirma Run-of-River Hydro Project', 'Turkey'],
  ['VCS-755', 'OTLUCA HPPs run-of-river hydro project', 'Turkey'],
  ['VCS-1148', 'Luofan 24MW Hydropower Project in Guizhou Province China', 'China'],
  ['VCS-1079', 'Bundled Wind Power Project in Jamnagar, Gujarat', 'India'],
  ['VCS-1044', 'Ziqiang 18MW Hydropower Project in Guizhou Province China', 'China'],
  ['VCS-619', '15 MW Grid Connected Renewable Energy Wind Turbine in Karnataka', 'India'],
  ['VCS-870', 'Wind Power Project by M/s Chhotabhai Jethabhai Patel & Co. (CJP) at Sinnar, Maharashtra', 'India'],
  ['VCS-264', 'Kargilik 24 MW Hydropower Plant, Turkey', 'Turkey'],
  ['VCS-936', 'Shiyazi Hydro power Project in Guizhou Province China', 'China'],
  ['VCS-330', 'Wutuhe Erji hydro power project in Guizhou Province, China', 'China'],
  ['VCS-713', 'KOYULHISAR HYDRO ELECTRICITY POWER PLANT', 'Turkey'],
  [
    'VCS-784',
    '1.6 MW Bundled Rice Husk Based Cogeneration Plant by M/s Milk food Limited (MFL) in Patiala (Punjab) & Moradabad (U.P) Districts',
    'India',
  ],
  ['VCS-699', 'Yiyang Xiushan Hydropower Project, P.R. China', 'China'],
  ['VCS-725', 'Shibeishan Wind Power Generation Project in Huilai County, Guangdong Province', 'China'],
  ['VCS-792', 'Tadi 16 MW Hydropower Project in Zhejiang Province', 'China'],
  ['VCS-670', 'Xiaoxi Hydropower Project', 'China'],
  [
    'VCS-245',
    'Bundled Grid Connected 2.9 M.W. Wind Power Project in India by Kamal Engineering Corporation [Unit of KEC Industries Ltd]',
    'India',
  ],
  ['VCS-293', 'Rice husk fired boiler of 6 ton capacity for process steam generation at Sukhbir', 'India'],
  ['VCS-624', '15 MW Biomass Residue Based Power Project at Ghazipur, India', 'India'],
  ['VCS-261', 'Bundled Biomass Based Thermal Energy Projects in U.P. & Punjab of Sukhbir Agro Energy Limited', 'India'],
  ['VCS-439', 'Yingpeng HFC23 Decompostion Project', 'China'],
  ['VCS-45', 'Zhoubai Hydroelectric Project', 'China'],
]
