export const operations = {
  get_activities: { path: "/activities", method: "get" },
  get_categories: { path: "/categories", method: "get" },
  get_countries: { path: "/countries", method: "get" },
  get_projects: { path: "/projects", method: "get" },
  get_purchases: { path: "/purchases", method: "get" },
  get_retirements: { path: "/retirements", method: "get" },
  post_users: { path: "/users", method: "post" },
  get_vintages: { path: "/vintages", method: "get" },
  "get_listings-id": { path: "/listings/:id", method: "get" },
  "get_projects-id": { path: "/projects/:id", method: "get" },
  "get_purchases-id": { path: "/purchases/:id", method: "get" },
  "get_retirements-id": { path: "/retirements/:id", method: "get" },
  "get_users-walletorhandle": { path: "/users/:walletOrHandle", method: "get" },
  "put_users-wallet": { path: "/users/:wallet", method: "put" },
  "get_projects-id-activity": { path: "/projects/:id/activity", method: "get" },
  "get_retirements-id-provenance": {
    path: "/retirements/:id/provenance",
    method: "get",
  },
} as const;
