query getPair($id: ID!) {
  pair(id: $id) {
    currentprice
  }
}

query getBySymbol($symbol: String) {
  tokens(where: { symbol: $symbol }) {
    id
  }
}

query getPoolPrices {
  prices: pairs {
    address: id
    price: currentprice
  }
}
