import KlimaRetirementsByTokenListConfigurationBase from "./KlimaRetirementsByListConfigurationBase";

export default class KlimaRetirementsByPoolListConfiguration extends KlimaRetirementsByTokenListConfigurationBase {}
