name: Block PRs for specific folders

on:
  pull_request:
    paths:
      - "cms/**"
      - "carbonmark/**"
      - "carbonmark-api/**"

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Block PR
        run: |
          echo "Carbonmark, Carbonmark API & the CMS have been migrated to https://github.com/Carbonmark/monorepo, please raise your pull request there"
          exit 1
