name: Checks

on:
  merge_group:
  pull_request:
    branches:
      - "main"
      - "staging"

# Allow the job to fetch a GitHub token
permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js in nvmrc file
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm ci
        env:
          TRANSLATIONIO_KEY_APP: ${{ secrets.TRANSLATIONIO_KEY_APP }}
          TRANSLATIONIO_KEY_SITE: ${{ secrets.TRANSLATIONIO_KEY_SITE }}
          TRANSLATIONIO_KEY_CARBONMARK: ${{ secrets.TRANSLATIONIO_KEY_CARBONMARK }}
      - name: List directory
        run: ls -al

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - run: npm run lint

  format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run format

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run test

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
