name: Deploy Carbonmark API
on:
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set short commit hash to environment variable
        run: echo "SHORT_COMMIT_HASH=$(echo ${GITHUB_SHA:0:7})" >> $GITHUB_ENV

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" carbonmark-api-${{ env.SHORT_COMMIT_HASH }}.klimadao.vercel.app
