name: CI
on:
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.18.1"

      - run: npm install npm@latest
      - run: npm run build-lib
      - run: npm run build-site
      - run: npm run build-app
