name: Schedule Auto Merge
# Change later for schedules on default branch every Monday and Thursday at 15h (8am PCT)
# - cron: '0 15 * * 1,4'
on:
  push:
    branches:
      - disable-for-now
    # Ignore changes in locale to not re-trigger this workflow, remove on final PR
    paths-ignore:
      - "**/locale/**"

jobs:
  call_update_translations:
    uses: ./.github/workflows/update_translations.yml
    with:
      environment: Release-staging
      branch: tmp-staging-test-branch
    secrets:
      PUSH_ACTOR_TOKEN: ${{ secrets.PUSH_ACTOR_TOKEN }}
      PUSH_ACTOR: ${{ secrets.PUSH_ACTOR }}
      TRANSLATIONIO_KEY_APP: ${{ secrets.TRANSLATIONIO_KEY_APP }}
      TRANSLATIONIO_KEY_SITE: ${{ secrets.TRANSLATIONIO_KEY_SITE }}

  call_wait_for_status:
    needs: [call_update_translations]
    uses: ./.github/workflows/wait_for_status_check.yml
    with:
      branch: tmp-staging-test-branch
    secrets:
      # take the default token here as no pushes are needed
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call_merge_staging:
    needs: [call_wait_for_status]
    if: needs.call_wait_for_status.outputs.status == 'success'
    uses: ./.github/workflows/merge_staging.yml
    with:
      environment: Release-staging
      staging_branch: tmp-staging-test-branch
      production_branch: tmp-main-test-branch
    secrets:
      PUSH_ACTOR_TOKEN: ${{ secrets.PUSH_ACTOR_TOKEN }}
      PUSH_ACTOR: ${{ secrets.PUSH_ACTOR }}
