name: Schedule Auto Merge
on:
  workflow_dispatch:
  schedule:
    # At 16:00 UTC (9am PDT) on every day-of-week from Monday through Thursday.
    - cron: "0 16 * * 1,2,3,4"

jobs:
  call_update_translations:
    uses: ./.github/workflows/update_translations.yml
    with:
      environment: Release-staging
      branch: staging
    secrets:
      PUSH_ACTOR_TOKEN: ${{ secrets.PUSH_ACTOR_TOKEN }}
      PUSH_ACTOR: ${{ secrets.PUSH_ACTOR }}
      TRANSLATIONIO_KEY_APP: ${{ secrets.TRANSLATIONIO_KEY_APP }}
      TRANSLATIONIO_KEY_SITE: ${{ secrets.TRANSLATIONIO_KEY_SITE }}

  call_wait_for_status:
    needs: [call_update_translations]
    uses: ./.github/workflows/wait_for_status_check.yml
    with:
      branch: staging
    secrets:
      # take the default token here as no pushes are needed
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call_merge_staging:
    needs: [call_wait_for_status]
    if: needs.call_wait_for_status.outputs.status == 'success'
    uses: ./.github/workflows/merge_staging.yml
    with:
      environment: Release-staging
      staging_branch: staging
      production_branch: main
    secrets:
      PUSH_ACTOR_TOKEN: ${{ secrets.PUSH_ACTOR_TOKEN }}
      PUSH_ACTOR: ${{ secrets.PUSH_ACTOR }}
